//! \file **********************************************************************
//! \brief Header Gestion des raccourcis globaux.
//! 
//! - Compilateur : GCC,MinGW
//!
//! \author Antoine Maleyrie.
//! \version 1.5
//! \date 13.12.12
//!
//! ****************************************************************************

#ifndef SHORTCUT_H
#define SHORTCUT_H

//WxWidgets
#include <wx/app.h>
#include <wx/thread.h>

//Stl
#include <vector>

#if defined(__UNIX__)
#include <X11/Xlib.h>
#include <X11/keysym.h>
#include <X11/XF86keysym.h>
#elif defined(__WXMSW__)
#include <windows.h>
#endif

#if defined(__UNIX__)
#define NB_KEY_MODIFIER 5
#elif defined(__WXMSW__)
#define NB_KEY_MODIFIER 4
#endif

// *****************************************************************************
// Enum Modifier_e
// *****************************************************************************

//! \brief Les modificateurs de touche.
enum Modifier_e
{
	#if defined(__DOXYGEN__)
	MODIFIER_CONTROL,	//!< Touche Ctrl, (version string : "Ctrl").
	MODIFIER_ALT,		//!< Touche Alt, (version string : "Alt").
	MODIFIER_ALTGR,		//!< Touche Alt Gr, (version string : "Altgr"). \note Seulement sous unix.
	MODIFIER_SHIFT,		//!< Touche Shift, (version string : "Shift").
	MODIFIER_SUPER,		//!< Touche Super(Win), (version string : "Super").
	MODIFIER_NONE  		//!< Le raccourci est probablement no valide.
	#elif defined(__UNIX__)
	MODIFIER_CONTROL = ControlMask,
	MODIFIER_ALT 	= Mod1Mask,
	MODIFIER_ALTGR 	= Mod5Mask,
	MODIFIER_SHIFT 	= ShiftMask,
	MODIFIER_SUPER 	= Mod4Mask,
	MODIFIER_NONE 	= -1 
	#elif defined(__WXMSW__)
	MODIFIER_CONTROL = MOD_CONTROL,
	MODIFIER_ALT 	= MOD_ALT,
	MODIFIER_SHIFT 	= MOD_SHIFT,
	MODIFIER_SUPER 	= MOD_WIN,
	MODIFIER_NONE 	= -1
	#endif
};

// *****************************************************************************
// Enum Key_e
// *****************************************************************************

enum Key_e
{
	#ifdef __UNIX__
	#ifdef XK_3270
	KEY_3270_DUPLICATE=		XK_3270_Duplicate,
	KEY_3270_FIELDMARK=		XK_3270_FieldMark,
	KEY_3270_RIGHT2=		XK_3270_Right2,
	KEY_3270_LEFT2=		XK_3270_Left2,
	KEY_3270_BACKTAB=		XK_3270_BackTab,
	KEY_3270_ERASEEOF=		XK_3270_EraseEOF,
	KEY_3270_ERASEINPUT=		XK_3270_EraseInput,
	KEY_3270_RESET=		XK_3270_Reset,
	KEY_3270_QUIT=		XK_3270_Quit,
	KEY_3270_PA1=		XK_3270_PA1,
	KEY_3270_PA2=		XK_3270_PA2,
	KEY_3270_PA3=		XK_3270_PA3,
	KEY_3270_TEST=		XK_3270_Test,
	KEY_3270_ATTN=		XK_3270_Attn,
	KEY_3270_CURSORBLINK=		XK_3270_CursorBlink,
	KEY_3270_ALTCURSOR=		XK_3270_AltCursor,
	KEY_3270_KEYCLICK=		XK_3270_KeyClick,
	KEY_3270_JUMP=		XK_3270_Jump,
	KEY_3270_IDENT=		XK_3270_Ident,
	KEY_3270_RULE=		XK_3270_Rule,
	KEY_3270_COPY=		XK_3270_Copy,
	KEY_3270_PLAY=		XK_3270_Play,
	KEY_3270_SETUP=		XK_3270_Setup,
	KEY_3270_RECORD=		XK_3270_Record,
	KEY_3270_CHANGESCREEN=		XK_3270_ChangeScreen,
	KEY_3270_DELETEWORD=		XK_3270_DeleteWord,
	KEY_3270_EXSELECT=		XK_3270_ExSelect,
	KEY_3270_CURSORSELECT=		XK_3270_CursorSelect,
	KEY_3270_PRINTSCREEN=		XK_3270_PrintScreen,
	KEY_3270_ENTER=		XK_3270_Enter,
	#endif
	#ifdef XK_APL
	KEY_LEFTCARET=		XK_leftcaret,
	KEY_RIGHTCARET=		XK_rightcaret,
	KEY_DOWNCARET=		XK_downcaret,
	KEY_UPCARET=		XK_upcaret,
	KEY_OVERBAR=		XK_overbar,
	KEY_DOWNTACK=		XK_downtack,
	KEY_UPSHOE=		XK_upshoe,
	KEY_DOWNSTILE=		XK_downstile,
	KEY_UNDERBAR=		XK_underbar,
	KEY_JOT=		XK_jot,
	KEY_QUAD=		XK_quad,
	KEY_UPTACK=		XK_uptack,
	KEY_CIRCLE=		XK_circle,
	KEY_UPSTILE=		XK_upstile,
	KEY_DOWNSHOE=		XK_downshoe,
	KEY_RIGHTSHOE=		XK_rightshoe,
	KEY_LEFTSHOE=		XK_leftshoe,
	KEY_LEFTTACK=		XK_lefttack,
	KEY_RIGHTTACK=		XK_righttack,
	#endif
	#ifdef XK_ARABIC
	KEY_FARSI_0=		XK_Farsi_0,
	KEY_FARSI_1=		XK_Farsi_1,
	KEY_FARSI_2=		XK_Farsi_2,
	KEY_FARSI_3=		XK_Farsi_3,
	KEY_FARSI_4=		XK_Farsi_4,
	KEY_FARSI_5=		XK_Farsi_5,
	KEY_FARSI_6=		XK_Farsi_6,
	KEY_FARSI_7=		XK_Farsi_7,
	KEY_FARSI_8=		XK_Farsi_8,
	KEY_FARSI_9=		XK_Farsi_9,
	KEY_ARABIC_PERCENT=		XK_Arabic_percent,
	KEY_ARABIC_SUPERSCRIPT_ALEF=		XK_Arabic_superscript_alef,
	KEY_ARABIC_TTEH=		XK_Arabic_tteh,
	KEY_ARABIC_PEH=		XK_Arabic_peh,
	KEY_ARABIC_TCHEH=		XK_Arabic_tcheh,
	KEY_ARABIC_DDAL=		XK_Arabic_ddal,
	KEY_ARABIC_RREH=		XK_Arabic_rreh,
	KEY_ARABIC_COMMA=		XK_Arabic_comma,
	KEY_ARABIC_FULLSTOP=		XK_Arabic_fullstop,
	KEY_ARABIC_0=		XK_Arabic_0,
	KEY_ARABIC_1=		XK_Arabic_1,
	KEY_ARABIC_2=		XK_Arabic_2,
	KEY_ARABIC_3=		XK_Arabic_3,
	KEY_ARABIC_4=		XK_Arabic_4,
	KEY_ARABIC_5=		XK_Arabic_5,
	KEY_ARABIC_6=		XK_Arabic_6,
	KEY_ARABIC_7=		XK_Arabic_7,
	KEY_ARABIC_8=		XK_Arabic_8,
	KEY_ARABIC_9=		XK_Arabic_9,
	KEY_ARABIC_SEMICOLON=		XK_Arabic_semicolon,
	KEY_ARABIC_QUESTION_MARK=		XK_Arabic_question_mark,
	KEY_ARABIC_HAMZA=		XK_Arabic_hamza,
	KEY_ARABIC_MADDAONALEF=		XK_Arabic_maddaonalef,
	KEY_ARABIC_HAMZAONALEF=		XK_Arabic_hamzaonalef,
	KEY_ARABIC_HAMZAONWAW=		XK_Arabic_hamzaonwaw,
	KEY_ARABIC_HAMZAUNDERALEF=		XK_Arabic_hamzaunderalef,
	KEY_ARABIC_HAMZAONYEH=		XK_Arabic_hamzaonyeh,
	KEY_ARABIC_ALEF=		XK_Arabic_alef,
	KEY_ARABIC_BEH=		XK_Arabic_beh,
	KEY_ARABIC_TEHMARBUTA=		XK_Arabic_tehmarbuta,
	KEY_ARABIC_TEH=		XK_Arabic_teh,
	KEY_ARABIC_THEH=		XK_Arabic_theh,
	KEY_ARABIC_JEEM=		XK_Arabic_jeem,
	KEY_ARABIC_HAH=		XK_Arabic_hah,
	KEY_ARABIC_KHAH=		XK_Arabic_khah,
	KEY_ARABIC_DAL=		XK_Arabic_dal,
	KEY_ARABIC_THAL=		XK_Arabic_thal,
	KEY_ARABIC_RA=		XK_Arabic_ra,
	KEY_ARABIC_ZAIN=		XK_Arabic_zain,
	KEY_ARABIC_SEEN=		XK_Arabic_seen,
	KEY_ARABIC_SHEEN=		XK_Arabic_sheen,
	KEY_ARABIC_SAD=		XK_Arabic_sad,
	KEY_ARABIC_DAD=		XK_Arabic_dad,
	KEY_ARABIC_TAH=		XK_Arabic_tah,
	KEY_ARABIC_ZAH=		XK_Arabic_zah,
	KEY_ARABIC_AIN=		XK_Arabic_ain,
	KEY_ARABIC_GHAIN=		XK_Arabic_ghain,
	KEY_ARABIC_TATWEEL=		XK_Arabic_tatweel,
	KEY_ARABIC_FEH=		XK_Arabic_feh,
	KEY_ARABIC_QAF=		XK_Arabic_qaf,
	KEY_ARABIC_KAF=		XK_Arabic_kaf,
	KEY_ARABIC_LAM=		XK_Arabic_lam,
	KEY_ARABIC_MEEM=		XK_Arabic_meem,
	KEY_ARABIC_NOON=		XK_Arabic_noon,
	KEY_ARABIC_HA=		XK_Arabic_ha,
	KEY_ARABIC_WAW=		XK_Arabic_waw,
	KEY_ARABIC_ALEFMAKSURA=		XK_Arabic_alefmaksura,
	KEY_ARABIC_YEH=		XK_Arabic_yeh,
	KEY_ARABIC_FATHATAN=		XK_Arabic_fathatan,
	KEY_ARABIC_DAMMATAN=		XK_Arabic_dammatan,
	KEY_ARABIC_KASRATAN=		XK_Arabic_kasratan,
	KEY_ARABIC_FATHA=		XK_Arabic_fatha,
	KEY_ARABIC_DAMMA=		XK_Arabic_damma,
	KEY_ARABIC_KASRA=		XK_Arabic_kasra,
	KEY_ARABIC_SHADDA=		XK_Arabic_shadda,
	KEY_ARABIC_SUKUN=		XK_Arabic_sukun,
	KEY_ARABIC_MADDA_ABOVE=		XK_Arabic_madda_above,
	KEY_ARABIC_HAMZA_ABOVE=		XK_Arabic_hamza_above,
	KEY_ARABIC_HAMZA_BELOW=		XK_Arabic_hamza_below,
	KEY_ARABIC_JEH=		XK_Arabic_jeh,
	KEY_ARABIC_VEH=		XK_Arabic_veh,
	KEY_ARABIC_KEHEH=		XK_Arabic_keheh,
	KEY_ARABIC_GAF=		XK_Arabic_gaf,
	KEY_ARABIC_NOON_GHUNNA=		XK_Arabic_noon_ghunna,
	KEY_ARABIC_HEH_DOACHASHMEE=		XK_Arabic_heh_doachashmee,
	KEY_FARSI_YEH=		XK_Farsi_yeh,
	KEY_ARABIC_FARSI_YEH=		XK_Arabic_farsi_yeh,
	KEY_ARABIC_YEH_BAREE=		XK_Arabic_yeh_baree,
	KEY_ARABIC_HEH_GOAL=		XK_Arabic_heh_goal,
	KEY_ARABIC_SWITCH=		XK_Arabic_switch,
	#endif
	#ifdef XK_ARMENIAN
	KEY_ARMENIAN_LIGATURE_EW=		XK_Armenian_ligature_ew,
	KEY_ARMENIAN_FULL_STOP=		XK_Armenian_full_stop,
	KEY_ARMENIAN_VERJAKET=		XK_Armenian_verjaket,
	KEY_ARMENIAN_SEPARATION_MARK=		XK_Armenian_separation_mark,
	KEY_ARMENIAN_BUT=		XK_Armenian_but,
	KEY_ARMENIAN_HYPHEN=		XK_Armenian_hyphen,
	KEY_ARMENIAN_YENTAMNA=		XK_Armenian_yentamna,
	KEY_ARMENIAN_EXCLAM=		XK_Armenian_exclam,
	KEY_ARMENIAN_AMANAK=		XK_Armenian_amanak,
	KEY_ARMENIAN_ACCENT=		XK_Armenian_accent,
	KEY_ARMENIAN_SHESHT=		XK_Armenian_shesht,
	KEY_ARMENIAN_QUESTION=		XK_Armenian_question,
	KEY_ARMENIAN_PARUYK=		XK_Armenian_paruyk,
	KEY_ARMENIAN_AYB=		XK_Armenian_AYB,
	KEY_ARMENIAN_BEN=		XK_Armenian_BEN,
	KEY_ARMENIAN_GIM=		XK_Armenian_GIM,
	KEY_ARMENIAN_DA=		XK_Armenian_DA,
	KEY_ARMENIAN_YECH=		XK_Armenian_YECH,
	KEY_ARMENIAN_ZA=		XK_Armenian_ZA,
	KEY_ARMENIAN_E=		XK_Armenian_E,
	KEY_ARMENIAN_AT=		XK_Armenian_AT,
	KEY_ARMENIAN_TO=		XK_Armenian_TO,
	KEY_ARMENIAN_ZHE=		XK_Armenian_ZHE,
	KEY_ARMENIAN_INI=		XK_Armenian_INI,
	KEY_ARMENIAN_LYUN=		XK_Armenian_LYUN,
	KEY_ARMENIAN_KHE=		XK_Armenian_KHE,
	KEY_ARMENIAN_TSA=		XK_Armenian_TSA,
	KEY_ARMENIAN_KEN=		XK_Armenian_KEN,
	KEY_ARMENIAN_HO=		XK_Armenian_HO,
	KEY_ARMENIAN_DZA=		XK_Armenian_DZA,
	KEY_ARMENIAN_GHAT=		XK_Armenian_GHAT,
	KEY_ARMENIAN_TCHE=		XK_Armenian_TCHE,
	KEY_ARMENIAN_MEN=		XK_Armenian_MEN,
	KEY_ARMENIAN_HI=		XK_Armenian_HI,
	KEY_ARMENIAN_NU=		XK_Armenian_NU,
	KEY_ARMENIAN_SHA=		XK_Armenian_SHA,
	KEY_ARMENIAN_VO=		XK_Armenian_VO,
	KEY_ARMENIAN_CHA=		XK_Armenian_CHA,
	KEY_ARMENIAN_PE=		XK_Armenian_PE,
	KEY_ARMENIAN_JE=		XK_Armenian_JE,
	KEY_ARMENIAN_RA=		XK_Armenian_RA,
	KEY_ARMENIAN_SE=		XK_Armenian_SE,
	KEY_ARMENIAN_VEV=		XK_Armenian_VEV,
	KEY_ARMENIAN_TYUN=		XK_Armenian_TYUN,
	KEY_ARMENIAN_RE=		XK_Armenian_RE,
	KEY_ARMENIAN_TSO=		XK_Armenian_TSO,
	KEY_ARMENIAN_VYUN=		XK_Armenian_VYUN,
	KEY_ARMENIAN_PYUR=		XK_Armenian_PYUR,
	KEY_ARMENIAN_KE=		XK_Armenian_KE,
	KEY_ARMENIAN_O=		XK_Armenian_O,
	KEY_ARMENIAN_FE=		XK_Armenian_FE,
	KEY_ARMENIAN_APOSTROPHE=		XK_Armenian_apostrophe,
	#endif
	#ifdef XK_BRAILLE
	KEY_BRAILLE_DOT_1=		XK_braille_dot_1,
	KEY_BRAILLE_DOT_2=		XK_braille_dot_2,
	KEY_BRAILLE_DOT_3=		XK_braille_dot_3,
	KEY_BRAILLE_DOT_4=		XK_braille_dot_4,
	KEY_BRAILLE_DOT_5=		XK_braille_dot_5,
	KEY_BRAILLE_DOT_6=		XK_braille_dot_6,
	KEY_BRAILLE_DOT_7=		XK_braille_dot_7,
	KEY_BRAILLE_DOT_8=		XK_braille_dot_8,
	KEY_BRAILLE_DOT_9=		XK_braille_dot_9,
	KEY_BRAILLE_DOT_10=		XK_braille_dot_10,
	KEY_BRAILLE_BLANK=		XK_braille_blank,
	KEY_BRAILLE_DOTS_1=		XK_braille_dots_1,
	KEY_BRAILLE_DOTS_2=		XK_braille_dots_2,
	KEY_BRAILLE_DOTS_12=		XK_braille_dots_12,
	KEY_BRAILLE_DOTS_3=		XK_braille_dots_3,
	KEY_BRAILLE_DOTS_13=		XK_braille_dots_13,
	KEY_BRAILLE_DOTS_23=		XK_braille_dots_23,
	KEY_BRAILLE_DOTS_123=		XK_braille_dots_123,
	KEY_BRAILLE_DOTS_4=		XK_braille_dots_4,
	KEY_BRAILLE_DOTS_14=		XK_braille_dots_14,
	KEY_BRAILLE_DOTS_24=		XK_braille_dots_24,
	KEY_BRAILLE_DOTS_124=		XK_braille_dots_124,
	KEY_BRAILLE_DOTS_34=		XK_braille_dots_34,
	KEY_BRAILLE_DOTS_134=		XK_braille_dots_134,
	KEY_BRAILLE_DOTS_234=		XK_braille_dots_234,
	KEY_BRAILLE_DOTS_1234=		XK_braille_dots_1234,
	KEY_BRAILLE_DOTS_5=		XK_braille_dots_5,
	KEY_BRAILLE_DOTS_15=		XK_braille_dots_15,
	KEY_BRAILLE_DOTS_25=		XK_braille_dots_25,
	KEY_BRAILLE_DOTS_125=		XK_braille_dots_125,
	KEY_BRAILLE_DOTS_35=		XK_braille_dots_35,
	KEY_BRAILLE_DOTS_135=		XK_braille_dots_135,
	KEY_BRAILLE_DOTS_235=		XK_braille_dots_235,
	KEY_BRAILLE_DOTS_1235=		XK_braille_dots_1235,
	KEY_BRAILLE_DOTS_45=		XK_braille_dots_45,
	KEY_BRAILLE_DOTS_145=		XK_braille_dots_145,
	KEY_BRAILLE_DOTS_245=		XK_braille_dots_245,
	KEY_BRAILLE_DOTS_1245=		XK_braille_dots_1245,
	KEY_BRAILLE_DOTS_345=		XK_braille_dots_345,
	KEY_BRAILLE_DOTS_1345=		XK_braille_dots_1345,
	KEY_BRAILLE_DOTS_2345=		XK_braille_dots_2345,
	KEY_BRAILLE_DOTS_12345=		XK_braille_dots_12345,
	KEY_BRAILLE_DOTS_6=		XK_braille_dots_6,
	KEY_BRAILLE_DOTS_16=		XK_braille_dots_16,
	KEY_BRAILLE_DOTS_26=		XK_braille_dots_26,
	KEY_BRAILLE_DOTS_126=		XK_braille_dots_126,
	KEY_BRAILLE_DOTS_36=		XK_braille_dots_36,
	KEY_BRAILLE_DOTS_136=		XK_braille_dots_136,
	KEY_BRAILLE_DOTS_236=		XK_braille_dots_236,
	KEY_BRAILLE_DOTS_1236=		XK_braille_dots_1236,
	KEY_BRAILLE_DOTS_46=		XK_braille_dots_46,
	KEY_BRAILLE_DOTS_146=		XK_braille_dots_146,
	KEY_BRAILLE_DOTS_246=		XK_braille_dots_246,
	KEY_BRAILLE_DOTS_1246=		XK_braille_dots_1246,
	KEY_BRAILLE_DOTS_346=		XK_braille_dots_346,
	KEY_BRAILLE_DOTS_1346=		XK_braille_dots_1346,
	KEY_BRAILLE_DOTS_2346=		XK_braille_dots_2346,
	KEY_BRAILLE_DOTS_12346=		XK_braille_dots_12346,
	KEY_BRAILLE_DOTS_56=		XK_braille_dots_56,
	KEY_BRAILLE_DOTS_156=		XK_braille_dots_156,
	KEY_BRAILLE_DOTS_256=		XK_braille_dots_256,
	KEY_BRAILLE_DOTS_1256=		XK_braille_dots_1256,
	KEY_BRAILLE_DOTS_356=		XK_braille_dots_356,
	KEY_BRAILLE_DOTS_1356=		XK_braille_dots_1356,
	KEY_BRAILLE_DOTS_2356=		XK_braille_dots_2356,
	KEY_BRAILLE_DOTS_12356=		XK_braille_dots_12356,
	KEY_BRAILLE_DOTS_456=		XK_braille_dots_456,
	KEY_BRAILLE_DOTS_1456=		XK_braille_dots_1456,
	KEY_BRAILLE_DOTS_2456=		XK_braille_dots_2456,
	KEY_BRAILLE_DOTS_12456=		XK_braille_dots_12456,
	KEY_BRAILLE_DOTS_3456=		XK_braille_dots_3456,
	KEY_BRAILLE_DOTS_13456=		XK_braille_dots_13456,
	KEY_BRAILLE_DOTS_23456=		XK_braille_dots_23456,
	KEY_BRAILLE_DOTS_123456=		XK_braille_dots_123456,
	KEY_BRAILLE_DOTS_7=		XK_braille_dots_7,
	KEY_BRAILLE_DOTS_17=		XK_braille_dots_17,
	KEY_BRAILLE_DOTS_27=		XK_braille_dots_27,
	KEY_BRAILLE_DOTS_127=		XK_braille_dots_127,
	KEY_BRAILLE_DOTS_37=		XK_braille_dots_37,
	KEY_BRAILLE_DOTS_137=		XK_braille_dots_137,
	KEY_BRAILLE_DOTS_237=		XK_braille_dots_237,
	KEY_BRAILLE_DOTS_1237=		XK_braille_dots_1237,
	KEY_BRAILLE_DOTS_47=		XK_braille_dots_47,
	KEY_BRAILLE_DOTS_147=		XK_braille_dots_147,
	KEY_BRAILLE_DOTS_247=		XK_braille_dots_247,
	KEY_BRAILLE_DOTS_1247=		XK_braille_dots_1247,
	KEY_BRAILLE_DOTS_347=		XK_braille_dots_347,
	KEY_BRAILLE_DOTS_1347=		XK_braille_dots_1347,
	KEY_BRAILLE_DOTS_2347=		XK_braille_dots_2347,
	KEY_BRAILLE_DOTS_12347=		XK_braille_dots_12347,
	KEY_BRAILLE_DOTS_57=		XK_braille_dots_57,
	KEY_BRAILLE_DOTS_157=		XK_braille_dots_157,
	KEY_BRAILLE_DOTS_257=		XK_braille_dots_257,
	KEY_BRAILLE_DOTS_1257=		XK_braille_dots_1257,
	KEY_BRAILLE_DOTS_357=		XK_braille_dots_357,
	KEY_BRAILLE_DOTS_1357=		XK_braille_dots_1357,
	KEY_BRAILLE_DOTS_2357=		XK_braille_dots_2357,
	KEY_BRAILLE_DOTS_12357=		XK_braille_dots_12357,
	KEY_BRAILLE_DOTS_457=		XK_braille_dots_457,
	KEY_BRAILLE_DOTS_1457=		XK_braille_dots_1457,
	KEY_BRAILLE_DOTS_2457=		XK_braille_dots_2457,
	KEY_BRAILLE_DOTS_12457=		XK_braille_dots_12457,
	KEY_BRAILLE_DOTS_3457=		XK_braille_dots_3457,
	KEY_BRAILLE_DOTS_13457=		XK_braille_dots_13457,
	KEY_BRAILLE_DOTS_23457=		XK_braille_dots_23457,
	KEY_BRAILLE_DOTS_123457=		XK_braille_dots_123457,
	KEY_BRAILLE_DOTS_67=		XK_braille_dots_67,
	KEY_BRAILLE_DOTS_167=		XK_braille_dots_167,
	KEY_BRAILLE_DOTS_267=		XK_braille_dots_267,
	KEY_BRAILLE_DOTS_1267=		XK_braille_dots_1267,
	KEY_BRAILLE_DOTS_367=		XK_braille_dots_367,
	KEY_BRAILLE_DOTS_1367=		XK_braille_dots_1367,
	KEY_BRAILLE_DOTS_2367=		XK_braille_dots_2367,
	KEY_BRAILLE_DOTS_12367=		XK_braille_dots_12367,
	KEY_BRAILLE_DOTS_467=		XK_braille_dots_467,
	KEY_BRAILLE_DOTS_1467=		XK_braille_dots_1467,
	KEY_BRAILLE_DOTS_2467=		XK_braille_dots_2467,
	KEY_BRAILLE_DOTS_12467=		XK_braille_dots_12467,
	KEY_BRAILLE_DOTS_3467=		XK_braille_dots_3467,
	KEY_BRAILLE_DOTS_13467=		XK_braille_dots_13467,
	KEY_BRAILLE_DOTS_23467=		XK_braille_dots_23467,
	KEY_BRAILLE_DOTS_123467=		XK_braille_dots_123467,
	KEY_BRAILLE_DOTS_567=		XK_braille_dots_567,
	KEY_BRAILLE_DOTS_1567=		XK_braille_dots_1567,
	KEY_BRAILLE_DOTS_2567=		XK_braille_dots_2567,
	KEY_BRAILLE_DOTS_12567=		XK_braille_dots_12567,
	KEY_BRAILLE_DOTS_3567=		XK_braille_dots_3567,
	KEY_BRAILLE_DOTS_13567=		XK_braille_dots_13567,
	KEY_BRAILLE_DOTS_23567=		XK_braille_dots_23567,
	KEY_BRAILLE_DOTS_123567=		XK_braille_dots_123567,
	KEY_BRAILLE_DOTS_4567=		XK_braille_dots_4567,
	KEY_BRAILLE_DOTS_14567=		XK_braille_dots_14567,
	KEY_BRAILLE_DOTS_24567=		XK_braille_dots_24567,
	KEY_BRAILLE_DOTS_124567=		XK_braille_dots_124567,
	KEY_BRAILLE_DOTS_34567=		XK_braille_dots_34567,
	KEY_BRAILLE_DOTS_134567=		XK_braille_dots_134567,
	KEY_BRAILLE_DOTS_234567=		XK_braille_dots_234567,
	KEY_BRAILLE_DOTS_1234567=		XK_braille_dots_1234567,
	KEY_BRAILLE_DOTS_8=		XK_braille_dots_8,
	KEY_BRAILLE_DOTS_18=		XK_braille_dots_18,
	KEY_BRAILLE_DOTS_28=		XK_braille_dots_28,
	KEY_BRAILLE_DOTS_128=		XK_braille_dots_128,
	KEY_BRAILLE_DOTS_38=		XK_braille_dots_38,
	KEY_BRAILLE_DOTS_138=		XK_braille_dots_138,
	KEY_BRAILLE_DOTS_238=		XK_braille_dots_238,
	KEY_BRAILLE_DOTS_1238=		XK_braille_dots_1238,
	KEY_BRAILLE_DOTS_48=		XK_braille_dots_48,
	KEY_BRAILLE_DOTS_148=		XK_braille_dots_148,
	KEY_BRAILLE_DOTS_248=		XK_braille_dots_248,
	KEY_BRAILLE_DOTS_1248=		XK_braille_dots_1248,
	KEY_BRAILLE_DOTS_348=		XK_braille_dots_348,
	KEY_BRAILLE_DOTS_1348=		XK_braille_dots_1348,
	KEY_BRAILLE_DOTS_2348=		XK_braille_dots_2348,
	KEY_BRAILLE_DOTS_12348=		XK_braille_dots_12348,
	KEY_BRAILLE_DOTS_58=		XK_braille_dots_58,
	KEY_BRAILLE_DOTS_158=		XK_braille_dots_158,
	KEY_BRAILLE_DOTS_258=		XK_braille_dots_258,
	KEY_BRAILLE_DOTS_1258=		XK_braille_dots_1258,
	KEY_BRAILLE_DOTS_358=		XK_braille_dots_358,
	KEY_BRAILLE_DOTS_1358=		XK_braille_dots_1358,
	KEY_BRAILLE_DOTS_2358=		XK_braille_dots_2358,
	KEY_BRAILLE_DOTS_12358=		XK_braille_dots_12358,
	KEY_BRAILLE_DOTS_458=		XK_braille_dots_458,
	KEY_BRAILLE_DOTS_1458=		XK_braille_dots_1458,
	KEY_BRAILLE_DOTS_2458=		XK_braille_dots_2458,
	KEY_BRAILLE_DOTS_12458=		XK_braille_dots_12458,
	KEY_BRAILLE_DOTS_3458=		XK_braille_dots_3458,
	KEY_BRAILLE_DOTS_13458=		XK_braille_dots_13458,
	KEY_BRAILLE_DOTS_23458=		XK_braille_dots_23458,
	KEY_BRAILLE_DOTS_123458=		XK_braille_dots_123458,
	KEY_BRAILLE_DOTS_68=		XK_braille_dots_68,
	KEY_BRAILLE_DOTS_168=		XK_braille_dots_168,
	KEY_BRAILLE_DOTS_268=		XK_braille_dots_268,
	KEY_BRAILLE_DOTS_1268=		XK_braille_dots_1268,
	KEY_BRAILLE_DOTS_368=		XK_braille_dots_368,
	KEY_BRAILLE_DOTS_1368=		XK_braille_dots_1368,
	KEY_BRAILLE_DOTS_2368=		XK_braille_dots_2368,
	KEY_BRAILLE_DOTS_12368=		XK_braille_dots_12368,
	KEY_BRAILLE_DOTS_468=		XK_braille_dots_468,
	KEY_BRAILLE_DOTS_1468=		XK_braille_dots_1468,
	KEY_BRAILLE_DOTS_2468=		XK_braille_dots_2468,
	KEY_BRAILLE_DOTS_12468=		XK_braille_dots_12468,
	KEY_BRAILLE_DOTS_3468=		XK_braille_dots_3468,
	KEY_BRAILLE_DOTS_13468=		XK_braille_dots_13468,
	KEY_BRAILLE_DOTS_23468=		XK_braille_dots_23468,
	KEY_BRAILLE_DOTS_123468=		XK_braille_dots_123468,
	KEY_BRAILLE_DOTS_568=		XK_braille_dots_568,
	KEY_BRAILLE_DOTS_1568=		XK_braille_dots_1568,
	KEY_BRAILLE_DOTS_2568=		XK_braille_dots_2568,
	KEY_BRAILLE_DOTS_12568=		XK_braille_dots_12568,
	KEY_BRAILLE_DOTS_3568=		XK_braille_dots_3568,
	KEY_BRAILLE_DOTS_13568=		XK_braille_dots_13568,
	KEY_BRAILLE_DOTS_23568=		XK_braille_dots_23568,
	KEY_BRAILLE_DOTS_123568=		XK_braille_dots_123568,
	KEY_BRAILLE_DOTS_4568=		XK_braille_dots_4568,
	KEY_BRAILLE_DOTS_14568=		XK_braille_dots_14568,
	KEY_BRAILLE_DOTS_24568=		XK_braille_dots_24568,
	KEY_BRAILLE_DOTS_124568=		XK_braille_dots_124568,
	KEY_BRAILLE_DOTS_34568=		XK_braille_dots_34568,
	KEY_BRAILLE_DOTS_134568=		XK_braille_dots_134568,
	KEY_BRAILLE_DOTS_234568=		XK_braille_dots_234568,
	KEY_BRAILLE_DOTS_1234568=		XK_braille_dots_1234568,
	KEY_BRAILLE_DOTS_78=		XK_braille_dots_78,
	KEY_BRAILLE_DOTS_178=		XK_braille_dots_178,
	KEY_BRAILLE_DOTS_278=		XK_braille_dots_278,
	KEY_BRAILLE_DOTS_1278=		XK_braille_dots_1278,
	KEY_BRAILLE_DOTS_378=		XK_braille_dots_378,
	KEY_BRAILLE_DOTS_1378=		XK_braille_dots_1378,
	KEY_BRAILLE_DOTS_2378=		XK_braille_dots_2378,
	KEY_BRAILLE_DOTS_12378=		XK_braille_dots_12378,
	KEY_BRAILLE_DOTS_478=		XK_braille_dots_478,
	KEY_BRAILLE_DOTS_1478=		XK_braille_dots_1478,
	KEY_BRAILLE_DOTS_2478=		XK_braille_dots_2478,
	KEY_BRAILLE_DOTS_12478=		XK_braille_dots_12478,
	KEY_BRAILLE_DOTS_3478=		XK_braille_dots_3478,
	KEY_BRAILLE_DOTS_13478=		XK_braille_dots_13478,
	KEY_BRAILLE_DOTS_23478=		XK_braille_dots_23478,
	KEY_BRAILLE_DOTS_123478=		XK_braille_dots_123478,
	KEY_BRAILLE_DOTS_578=		XK_braille_dots_578,
	KEY_BRAILLE_DOTS_1578=		XK_braille_dots_1578,
	KEY_BRAILLE_DOTS_2578=		XK_braille_dots_2578,
	KEY_BRAILLE_DOTS_12578=		XK_braille_dots_12578,
	KEY_BRAILLE_DOTS_3578=		XK_braille_dots_3578,
	KEY_BRAILLE_DOTS_13578=		XK_braille_dots_13578,
	KEY_BRAILLE_DOTS_23578=		XK_braille_dots_23578,
	KEY_BRAILLE_DOTS_123578=		XK_braille_dots_123578,
	KEY_BRAILLE_DOTS_4578=		XK_braille_dots_4578,
	KEY_BRAILLE_DOTS_14578=		XK_braille_dots_14578,
	KEY_BRAILLE_DOTS_24578=		XK_braille_dots_24578,
	KEY_BRAILLE_DOTS_124578=		XK_braille_dots_124578,
	KEY_BRAILLE_DOTS_34578=		XK_braille_dots_34578,
	KEY_BRAILLE_DOTS_134578=		XK_braille_dots_134578,
	KEY_BRAILLE_DOTS_234578=		XK_braille_dots_234578,
	KEY_BRAILLE_DOTS_1234578=		XK_braille_dots_1234578,
	KEY_BRAILLE_DOTS_678=		XK_braille_dots_678,
	KEY_BRAILLE_DOTS_1678=		XK_braille_dots_1678,
	KEY_BRAILLE_DOTS_2678=		XK_braille_dots_2678,
	KEY_BRAILLE_DOTS_12678=		XK_braille_dots_12678,
	KEY_BRAILLE_DOTS_3678=		XK_braille_dots_3678,
	KEY_BRAILLE_DOTS_13678=		XK_braille_dots_13678,
	KEY_BRAILLE_DOTS_23678=		XK_braille_dots_23678,
	KEY_BRAILLE_DOTS_123678=		XK_braille_dots_123678,
	KEY_BRAILLE_DOTS_4678=		XK_braille_dots_4678,
	KEY_BRAILLE_DOTS_14678=		XK_braille_dots_14678,
	KEY_BRAILLE_DOTS_24678=		XK_braille_dots_24678,
	KEY_BRAILLE_DOTS_124678=		XK_braille_dots_124678,
	KEY_BRAILLE_DOTS_34678=		XK_braille_dots_34678,
	KEY_BRAILLE_DOTS_134678=		XK_braille_dots_134678,
	KEY_BRAILLE_DOTS_234678=		XK_braille_dots_234678,
	KEY_BRAILLE_DOTS_1234678=		XK_braille_dots_1234678,
	KEY_BRAILLE_DOTS_5678=		XK_braille_dots_5678,
	KEY_BRAILLE_DOTS_15678=		XK_braille_dots_15678,
	KEY_BRAILLE_DOTS_25678=		XK_braille_dots_25678,
	KEY_BRAILLE_DOTS_125678=		XK_braille_dots_125678,
	KEY_BRAILLE_DOTS_35678=		XK_braille_dots_35678,
	KEY_BRAILLE_DOTS_135678=		XK_braille_dots_135678,
	KEY_BRAILLE_DOTS_235678=		XK_braille_dots_235678,
	KEY_BRAILLE_DOTS_1235678=		XK_braille_dots_1235678,
	KEY_BRAILLE_DOTS_45678=		XK_braille_dots_45678,
	KEY_BRAILLE_DOTS_145678=		XK_braille_dots_145678,
	KEY_BRAILLE_DOTS_245678=		XK_braille_dots_245678,
	KEY_BRAILLE_DOTS_1245678=		XK_braille_dots_1245678,
	KEY_BRAILLE_DOTS_345678=		XK_braille_dots_345678,
	KEY_BRAILLE_DOTS_1345678=		XK_braille_dots_1345678,
	KEY_BRAILLE_DOTS_2345678=		XK_braille_dots_2345678,
	KEY_BRAILLE_DOTS_12345678=		XK_braille_dots_12345678,
	#endif
	#ifdef XK_CAUCASUS
	KEY_XABOVEDOT=		XK_Xabovedot,
	KEY_IBREVE=		XK_Ibreve,
	KEY_ZSTROKE=		XK_Zstroke,
	KEY_GCARON=		XK_Gcaron,
	KEY_OCARON=		XK_Ocaron,
	KEY_OBARRED=		XK_Obarred,
	KEY_SCHWA=		XK_SCHWA,
	KEY_EZH=		XK_EZH,
	KEY_LBELOWDOT=		XK_Lbelowdot,
	#endif
	#ifdef XK_CURRENCY
	KEY_ECUSIGN=		XK_EcuSign,
	KEY_COLONSIGN=		XK_ColonSign,
	KEY_CRUZEIROSIGN=		XK_CruzeiroSign,
	KEY_FFRANCSIGN=		XK_FFrancSign,
	KEY_LIRASIGN=		XK_LiraSign,
	KEY_MILLSIGN=		XK_MillSign,
	KEY_NAIRASIGN=		XK_NairaSign,
	KEY_PESETASIGN=		XK_PesetaSign,
	KEY_RUPEESIGN=		XK_RupeeSign,
	KEY_WONSIGN=		XK_WonSign,
	KEY_NEWSHEQELSIGN=		XK_NewSheqelSign,
	KEY_DONGSIGN=		XK_DongSign,
	KEY_EUROSIGN=		XK_EuroSign,
	#endif
	#ifdef XK_CYRILLIC
	KEY_CYRILLIC_GHE_BAR=		XK_Cyrillic_GHE_bar,
	KEY_CYRILLIC_ZHE_DESCENDER=		XK_Cyrillic_ZHE_descender,
	KEY_CYRILLIC_KA_DESCENDER=		XK_Cyrillic_KA_descender,
	KEY_CYRILLIC_KA_VERTSTROKE=		XK_Cyrillic_KA_vertstroke,
	KEY_CYRILLIC_EN_DESCENDER=		XK_Cyrillic_EN_descender,
	KEY_CYRILLIC_U_STRAIGHT=		XK_Cyrillic_U_straight,
	KEY_CYRILLIC_U_STRAIGHT_BAR=		XK_Cyrillic_U_straight_bar,
	KEY_CYRILLIC_HA_DESCENDER=		XK_Cyrillic_HA_descender,
	KEY_CYRILLIC_CHE_DESCENDER=		XK_Cyrillic_CHE_descender,
	KEY_CYRILLIC_CHE_VERTSTROKE=		XK_Cyrillic_CHE_vertstroke,
	KEY_CYRILLIC_SHHA=		XK_Cyrillic_SHHA,
	KEY_CYRILLIC_SCHWA=		XK_Cyrillic_SCHWA,
	KEY_CYRILLIC_I_MACRON=		XK_Cyrillic_I_macron,
	KEY_CYRILLIC_O_BAR=		XK_Cyrillic_O_bar,
	KEY_CYRILLIC_U_MACRON=		XK_Cyrillic_U_macron,
	KEY_SERBIAN_DJE=		XK_Serbian_dje,
	KEY_MACEDONIA_GJE=		XK_Macedonia_gje,
	KEY_CYRILLIC_IO=		XK_Cyrillic_io,
	KEY_UKRAINIAN_IE=		XK_Ukrainian_ie,
	KEY_MACEDONIA_DSE=		XK_Macedonia_dse,
	KEY_UKRAINIAN_I=		XK_Ukrainian_i,
	KEY_UKRAINIAN_YI=		XK_Ukrainian_yi,
	KEY_CYRILLIC_JE=		XK_Cyrillic_je,
	KEY_CYRILLIC_LJE=		XK_Cyrillic_lje,
	KEY_CYRILLIC_NJE=		XK_Cyrillic_nje,
	KEY_SERBIAN_TSHE=		XK_Serbian_tshe,
	KEY_MACEDONIA_KJE=		XK_Macedonia_kje,
	KEY_UKRAINIAN_GHE_WITH_UPTURN=		XK_Ukrainian_ghe_with_upturn,
	KEY_BYELORUSSIAN_SHORTU=		XK_Byelorussian_shortu,
	KEY_CYRILLIC_DZHE=		XK_Cyrillic_dzhe,
	KEY_NUMEROSIGN=		XK_numerosign,
	KEY_CYRILLIC_YU=		XK_Cyrillic_yu,
	KEY_CYRILLIC_A=		XK_Cyrillic_a,
	KEY_CYRILLIC_BE=		XK_Cyrillic_be,
	KEY_CYRILLIC_TSE=		XK_Cyrillic_tse,
	KEY_CYRILLIC_DE=		XK_Cyrillic_de,
	KEY_CYRILLIC_IE=		XK_Cyrillic_ie,
	KEY_CYRILLIC_EF=		XK_Cyrillic_ef,
	KEY_CYRILLIC_GHE=		XK_Cyrillic_ghe,
	KEY_CYRILLIC_HA=		XK_Cyrillic_ha,
	KEY_CYRILLIC_I=		XK_Cyrillic_i,
	KEY_CYRILLIC_SHORTI=		XK_Cyrillic_shorti,
	KEY_CYRILLIC_KA=		XK_Cyrillic_ka,
	KEY_CYRILLIC_EL=		XK_Cyrillic_el,
	KEY_CYRILLIC_EM=		XK_Cyrillic_em,
	KEY_CYRILLIC_EN=		XK_Cyrillic_en,
	KEY_CYRILLIC_O=		XK_Cyrillic_o,
	KEY_CYRILLIC_PE=		XK_Cyrillic_pe,
	KEY_CYRILLIC_YA=		XK_Cyrillic_ya,
	KEY_CYRILLIC_ER=		XK_Cyrillic_er,
	KEY_CYRILLIC_ES=		XK_Cyrillic_es,
	KEY_CYRILLIC_TE=		XK_Cyrillic_te,
	KEY_CYRILLIC_U=		XK_Cyrillic_u,
	KEY_CYRILLIC_ZHE=		XK_Cyrillic_zhe,
	KEY_CYRILLIC_VE=		XK_Cyrillic_ve,
	KEY_CYRILLIC_SOFTSIGN=		XK_Cyrillic_softsign,
	KEY_CYRILLIC_YERU=		XK_Cyrillic_yeru,
	KEY_CYRILLIC_ZE=		XK_Cyrillic_ze,
	KEY_CYRILLIC_SHA=		XK_Cyrillic_sha,
	KEY_CYRILLIC_E=		XK_Cyrillic_e,
	KEY_CYRILLIC_SHCHA=		XK_Cyrillic_shcha,
	KEY_CYRILLIC_CHE=		XK_Cyrillic_che,
	KEY_CYRILLIC_HARDSIGN=		XK_Cyrillic_hardsign,
	#endif
	#ifdef XK_GEORGIAN
	KEY_GEORGIAN_AN=		XK_Georgian_an,
	KEY_GEORGIAN_BAN=		XK_Georgian_ban,
	KEY_GEORGIAN_GAN=		XK_Georgian_gan,
	KEY_GEORGIAN_DON=		XK_Georgian_don,
	KEY_GEORGIAN_EN=		XK_Georgian_en,
	KEY_GEORGIAN_VIN=		XK_Georgian_vin,
	KEY_GEORGIAN_ZEN=		XK_Georgian_zen,
	KEY_GEORGIAN_TAN=		XK_Georgian_tan,
	KEY_GEORGIAN_IN=		XK_Georgian_in,
	KEY_GEORGIAN_KAN=		XK_Georgian_kan,
	KEY_GEORGIAN_LAS=		XK_Georgian_las,
	KEY_GEORGIAN_MAN=		XK_Georgian_man,
	KEY_GEORGIAN_NAR=		XK_Georgian_nar,
	KEY_GEORGIAN_ON=		XK_Georgian_on,
	KEY_GEORGIAN_PAR=		XK_Georgian_par,
	KEY_GEORGIAN_ZHAR=		XK_Georgian_zhar,
	KEY_GEORGIAN_RAE=		XK_Georgian_rae,
	KEY_GEORGIAN_SAN=		XK_Georgian_san,
	KEY_GEORGIAN_TAR=		XK_Georgian_tar,
	KEY_GEORGIAN_UN=		XK_Georgian_un,
	KEY_GEORGIAN_PHAR=		XK_Georgian_phar,
	KEY_GEORGIAN_KHAR=		XK_Georgian_khar,
	KEY_GEORGIAN_GHAN=		XK_Georgian_ghan,
	KEY_GEORGIAN_QAR=		XK_Georgian_qar,
	KEY_GEORGIAN_SHIN=		XK_Georgian_shin,
	KEY_GEORGIAN_CHIN=		XK_Georgian_chin,
	KEY_GEORGIAN_CAN=		XK_Georgian_can,
	KEY_GEORGIAN_JIL=		XK_Georgian_jil,
	KEY_GEORGIAN_CIL=		XK_Georgian_cil,
	KEY_GEORGIAN_CHAR=		XK_Georgian_char,
	KEY_GEORGIAN_XAN=		XK_Georgian_xan,
	KEY_GEORGIAN_JHAN=		XK_Georgian_jhan,
	KEY_GEORGIAN_HAE=		XK_Georgian_hae,
	KEY_GEORGIAN_HE=		XK_Georgian_he,
	KEY_GEORGIAN_HIE=		XK_Georgian_hie,
	KEY_GEORGIAN_WE=		XK_Georgian_we,
	KEY_GEORGIAN_HAR=		XK_Georgian_har,
	KEY_GEORGIAN_HOE=		XK_Georgian_hoe,
	KEY_GEORGIAN_FI=		XK_Georgian_fi,
	#endif
	#ifdef XK_GREEK
	KEY_GREEK_ALPHAACCENT=		XK_Greek_ALPHAaccent,
	KEY_GREEK_EPSILONACCENT=		XK_Greek_EPSILONaccent,
	KEY_GREEK_ETAACCENT=		XK_Greek_ETAaccent,
	KEY_GREEK_IOTAACCENT=		XK_Greek_IOTAaccent,
	KEY_GREEK_IOTADIERESIS=		XK_Greek_IOTAdieresis,
	KEY_GREEK_IOTADIAERESIS=		XK_Greek_IOTAdiaeresis,
	KEY_GREEK_OMICRONACCENT=		XK_Greek_OMICRONaccent,
	KEY_GREEK_UPSILONACCENT=		XK_Greek_UPSILONaccent,
	KEY_GREEK_UPSILONDIERESIS=		XK_Greek_UPSILONdieresis,
	KEY_GREEK_OMEGAACCENT=		XK_Greek_OMEGAaccent,
	KEY_GREEK_ACCENTDIERESIS=		XK_Greek_accentdieresis,
	KEY_GREEK_HORIZBAR=		XK_Greek_horizbar,
	KEY_GREEK_IOTAACCENTDIERESIS=		XK_Greek_iotaaccentdieresis,
	KEY_GREEK_UPSILONACCENTDIERESIS=		XK_Greek_upsilonaccentdieresis,
	KEY_GREEK_ALPHA=		XK_Greek_ALPHA,
	KEY_GREEK_BETA=		XK_Greek_BETA,
	KEY_GREEK_GAMMA=		XK_Greek_GAMMA,
	KEY_GREEK_DELTA=		XK_Greek_DELTA,
	KEY_GREEK_EPSILON=		XK_Greek_EPSILON,
	KEY_GREEK_ZETA=		XK_Greek_ZETA,
	KEY_GREEK_ETA=		XK_Greek_ETA,
	KEY_GREEK_THETA=		XK_Greek_THETA,
	KEY_GREEK_IOTA=		XK_Greek_IOTA,
	KEY_GREEK_KAPPA=		XK_Greek_KAPPA,
	KEY_GREEK_LAMDA=		XK_Greek_LAMDA,
	KEY_GREEK_LAMBDA=		XK_Greek_LAMBDA,
	KEY_GREEK_MU=		XK_Greek_MU,
	KEY_GREEK_NU=		XK_Greek_NU,
	KEY_GREEK_XI=		XK_Greek_XI,
	KEY_GREEK_OMICRON=		XK_Greek_OMICRON,
	KEY_GREEK_PI=		XK_Greek_PI,
	KEY_GREEK_RHO=		XK_Greek_RHO,
	KEY_GREEK_SIGMA=		XK_Greek_SIGMA,
	KEY_GREEK_TAU=		XK_Greek_TAU,
	KEY_GREEK_UPSILON=		XK_Greek_UPSILON,
	KEY_GREEK_PHI=		XK_Greek_PHI,
	KEY_GREEK_CHI=		XK_Greek_CHI,
	KEY_GREEK_PSI=		XK_Greek_PSI,
	KEY_GREEK_OMEGA=		XK_Greek_OMEGA,
	KEY_GREEK_FINALSMALLSIGMA=		XK_Greek_finalsmallsigma,
	KEY_GREEK_SWITCH=		XK_Greek_switch,
	#endif
	#ifdef XK_HEBREW
	KEY_HEBREW_DOUBLELOWLINE=		XK_hebrew_doublelowline,
	KEY_HEBREW_ALEPH=		XK_hebrew_aleph,
	KEY_HEBREW_BET=		XK_hebrew_bet,
	KEY_HEBREW_GIMEL=		XK_hebrew_gimel,
	KEY_HEBREW_DALET=		XK_hebrew_dalet,
	KEY_HEBREW_HE=		XK_hebrew_he,
	KEY_HEBREW_WAW=		XK_hebrew_waw,
	KEY_HEBREW_ZAIN=		XK_hebrew_zain,
	KEY_HEBREW_CHET=		XK_hebrew_chet,
	KEY_HEBREW_TET=		XK_hebrew_tet,
	KEY_HEBREW_YOD=		XK_hebrew_yod,
	KEY_HEBREW_FINALKAPH=		XK_hebrew_finalkaph,
	KEY_HEBREW_KAPH=		XK_hebrew_kaph,
	KEY_HEBREW_LAMED=		XK_hebrew_lamed,
	KEY_HEBREW_FINALMEM=		XK_hebrew_finalmem,
	KEY_HEBREW_MEM=		XK_hebrew_mem,
	KEY_HEBREW_FINALNUN=		XK_hebrew_finalnun,
	KEY_HEBREW_NUN=		XK_hebrew_nun,
	KEY_HEBREW_SAMECH=		XK_hebrew_samech,
	KEY_HEBREW_AYIN=		XK_hebrew_ayin,
	KEY_HEBREW_FINALPE=		XK_hebrew_finalpe,
	KEY_HEBREW_PE=		XK_hebrew_pe,
	KEY_HEBREW_FINALZADE=		XK_hebrew_finalzade,
	KEY_HEBREW_ZADE=		XK_hebrew_zade,
	KEY_HEBREW_QOPH=		XK_hebrew_qoph,
	KEY_HEBREW_RESH=		XK_hebrew_resh,
	KEY_HEBREW_SHIN=		XK_hebrew_shin,
	KEY_HEBREW_TAW=		XK_hebrew_taw,
	KEY_HEBREW_SWITCH=		XK_Hebrew_switch,
	#endif
	#ifdef XK_KATAKANA
	KEY_OVERLINE=		XK_overline,
	KEY_KANA_FULLSTOP=		XK_kana_fullstop,
	KEY_KANA_OPENINGBRACKET=		XK_kana_openingbracket,
	KEY_KANA_CLOSINGBRACKET=		XK_kana_closingbracket,
	KEY_KANA_COMMA=		XK_kana_comma,
	KEY_KANA_CONJUNCTIVE=		XK_kana_conjunctive,
	KEY_KANA_WO=		XK_kana_WO,
	KEY_KANA_A=		XK_kana_a,
	KEY_KANA_I=		XK_kana_i,
	KEY_KANA_U=		XK_kana_u,
	KEY_KANA_E=		XK_kana_e,
	KEY_KANA_O=		XK_kana_o,
	KEY_KANA_YA=		XK_kana_ya,
	KEY_KANA_YU=		XK_kana_yu,
	KEY_KANA_YO=		XK_kana_yo,
	KEY_KANA_TSU=		XK_kana_tsu,
	KEY_PROLONGEDSOUND=		XK_prolongedsound,
	KEY_KANA_KA=		XK_kana_KA,
	KEY_KANA_KI=		XK_kana_KI,
	KEY_KANA_KU=		XK_kana_KU,
	KEY_KANA_KE=		XK_kana_KE,
	KEY_KANA_KO=		XK_kana_KO,
	KEY_KANA_SA=		XK_kana_SA,
	KEY_KANA_SHI=		XK_kana_SHI,
	KEY_KANA_SU=		XK_kana_SU,
	KEY_KANA_SE=		XK_kana_SE,
	KEY_KANA_SO=		XK_kana_SO,
	KEY_KANA_TA=		XK_kana_TA,
	KEY_KANA_CHI=		XK_kana_CHI,
	KEY_KANA_TE=		XK_kana_TE,
	KEY_KANA_TO=		XK_kana_TO,
	KEY_KANA_NA=		XK_kana_NA,
	KEY_KANA_NI=		XK_kana_NI,
	KEY_KANA_NU=		XK_kana_NU,
	KEY_KANA_NE=		XK_kana_NE,
	KEY_KANA_NO=		XK_kana_NO,
	KEY_KANA_HA=		XK_kana_HA,
	KEY_KANA_HI=		XK_kana_HI,
	KEY_KANA_FU=		XK_kana_FU,
	KEY_KANA_HE=		XK_kana_HE,
	KEY_KANA_HO=		XK_kana_HO,
	KEY_KANA_MA=		XK_kana_MA,
	KEY_KANA_MI=		XK_kana_MI,
	KEY_KANA_MU=		XK_kana_MU,
	KEY_KANA_ME=		XK_kana_ME,
	KEY_KANA_MO=		XK_kana_MO,
	KEY_KANA_RA=		XK_kana_RA,
	KEY_KANA_RI=		XK_kana_RI,
	KEY_KANA_RU=		XK_kana_RU,
	KEY_KANA_RE=		XK_kana_RE,
	KEY_KANA_RO=		XK_kana_RO,
	KEY_KANA_WA=		XK_kana_WA,
	KEY_KANA_N=		XK_kana_N,
	KEY_VOICEDSOUND=		XK_voicedsound,
	KEY_SEMIVOICEDSOUND=		XK_semivoicedsound,
	KEY_KANA_SWITCH=		XK_kana_switch,
	#endif
	#ifdef XK_KOREAN
	KEY_HANGUL=		XK_Hangul,
	KEY_HANGUL_START=		XK_Hangul_Start,
	KEY_HANGUL_END=		XK_Hangul_End,
	KEY_HANGUL_HANJA=		XK_Hangul_Hanja,
	KEY_HANGUL_JAMO=		XK_Hangul_Jamo,
	KEY_HANGUL_ROMAJA=		XK_Hangul_Romaja,
	KEY_HANGUL_CODEINPUT=		XK_Hangul_Codeinput,
	KEY_HANGUL_JEONJA=		XK_Hangul_Jeonja,
	KEY_HANGUL_BANJA=		XK_Hangul_Banja,
	KEY_HANGUL_PREHANJA=		XK_Hangul_PreHanja,
	KEY_HANGUL_POSTHANJA=		XK_Hangul_PostHanja,
	KEY_HANGUL_SINGLECANDIDATE=		XK_Hangul_SingleCandidate,
	KEY_HANGUL_MULTIPLECANDIDATE=		XK_Hangul_MultipleCandidate,
	KEY_HANGUL_PREVIOUSCANDIDATE=		XK_Hangul_PreviousCandidate,
	KEY_HANGUL_SPECIAL=		XK_Hangul_Special,
	KEY_HANGUL_SWITCH=		XK_Hangul_switch,
	KEY_HANGUL_KIYEOG=		XK_Hangul_Kiyeog,
	KEY_HANGUL_SSANGKIYEOG=		XK_Hangul_SsangKiyeog,
	KEY_HANGUL_KIYEOGSIOS=		XK_Hangul_KiyeogSios,
	KEY_HANGUL_NIEUN=		XK_Hangul_Nieun,
	KEY_HANGUL_NIEUNJIEUJ=		XK_Hangul_NieunJieuj,
	KEY_HANGUL_NIEUNHIEUH=		XK_Hangul_NieunHieuh,
	KEY_HANGUL_DIKEUD=		XK_Hangul_Dikeud,
	KEY_HANGUL_SSANGDIKEUD=		XK_Hangul_SsangDikeud,
	KEY_HANGUL_RIEUL=		XK_Hangul_Rieul,
	KEY_HANGUL_RIEULKIYEOG=		XK_Hangul_RieulKiyeog,
	KEY_HANGUL_RIEULMIEUM=		XK_Hangul_RieulMieum,
	KEY_HANGUL_RIEULPIEUB=		XK_Hangul_RieulPieub,
	KEY_HANGUL_RIEULSIOS=		XK_Hangul_RieulSios,
	KEY_HANGUL_RIEULTIEUT=		XK_Hangul_RieulTieut,
	KEY_HANGUL_RIEULPHIEUF=		XK_Hangul_RieulPhieuf,
	KEY_HANGUL_RIEULHIEUH=		XK_Hangul_RieulHieuh,
	KEY_HANGUL_MIEUM=		XK_Hangul_Mieum,
	KEY_HANGUL_PIEUB=		XK_Hangul_Pieub,
	KEY_HANGUL_SSANGPIEUB=		XK_Hangul_SsangPieub,
	KEY_HANGUL_PIEUBSIOS=		XK_Hangul_PieubSios,
	KEY_HANGUL_SIOS=		XK_Hangul_Sios,
	KEY_HANGUL_SSANGSIOS=		XK_Hangul_SsangSios,
	KEY_HANGUL_IEUNG=		XK_Hangul_Ieung,
	KEY_HANGUL_JIEUJ=		XK_Hangul_Jieuj,
	KEY_HANGUL_SSANGJIEUJ=		XK_Hangul_SsangJieuj,
	KEY_HANGUL_CIEUC=		XK_Hangul_Cieuc,
	KEY_HANGUL_KHIEUQ=		XK_Hangul_Khieuq,
	KEY_HANGUL_TIEUT=		XK_Hangul_Tieut,
	KEY_HANGUL_PHIEUF=		XK_Hangul_Phieuf,
	KEY_HANGUL_HIEUH=		XK_Hangul_Hieuh,
	KEY_HANGUL_A=		XK_Hangul_A,
	KEY_HANGUL_AE=		XK_Hangul_AE,
	KEY_HANGUL_YA=		XK_Hangul_YA,
	KEY_HANGUL_YAE=		XK_Hangul_YAE,
	KEY_HANGUL_EO=		XK_Hangul_EO,
	KEY_HANGUL_E=		XK_Hangul_E,
	KEY_HANGUL_YEO=		XK_Hangul_YEO,
	KEY_HANGUL_YE=		XK_Hangul_YE,
	KEY_HANGUL_O=		XK_Hangul_O,
	KEY_HANGUL_WA=		XK_Hangul_WA,
	KEY_HANGUL_WAE=		XK_Hangul_WAE,
	KEY_HANGUL_OE=		XK_Hangul_OE,
	KEY_HANGUL_YO=		XK_Hangul_YO,
	KEY_HANGUL_U=		XK_Hangul_U,
	KEY_HANGUL_WEO=		XK_Hangul_WEO,
	KEY_HANGUL_WE=		XK_Hangul_WE,
	KEY_HANGUL_WI=		XK_Hangul_WI,
	KEY_HANGUL_YU=		XK_Hangul_YU,
	KEY_HANGUL_EU=		XK_Hangul_EU,
	KEY_HANGUL_YI=		XK_Hangul_YI,
	KEY_HANGUL_I=		XK_Hangul_I,
	KEY_HANGUL_J_KIYEOG=		XK_Hangul_J_Kiyeog,
	KEY_HANGUL_J_SSANGKIYEOG=		XK_Hangul_J_SsangKiyeog,
	KEY_HANGUL_J_KIYEOGSIOS=		XK_Hangul_J_KiyeogSios,
	KEY_HANGUL_J_NIEUN=		XK_Hangul_J_Nieun,
	KEY_HANGUL_J_NIEUNJIEUJ=		XK_Hangul_J_NieunJieuj,
	KEY_HANGUL_J_NIEUNHIEUH=		XK_Hangul_J_NieunHieuh,
	KEY_HANGUL_J_DIKEUD=		XK_Hangul_J_Dikeud,
	KEY_HANGUL_J_RIEUL=		XK_Hangul_J_Rieul,
	KEY_HANGUL_J_RIEULKIYEOG=		XK_Hangul_J_RieulKiyeog,
	KEY_HANGUL_J_RIEULMIEUM=		XK_Hangul_J_RieulMieum,
	KEY_HANGUL_J_RIEULPIEUB=		XK_Hangul_J_RieulPieub,
	KEY_HANGUL_J_RIEULSIOS=		XK_Hangul_J_RieulSios,
	KEY_HANGUL_J_RIEULTIEUT=		XK_Hangul_J_RieulTieut,
	KEY_HANGUL_J_RIEULPHIEUF=		XK_Hangul_J_RieulPhieuf,
	KEY_HANGUL_J_RIEULHIEUH=		XK_Hangul_J_RieulHieuh,
	KEY_HANGUL_J_MIEUM=		XK_Hangul_J_Mieum,
	KEY_HANGUL_J_PIEUB=		XK_Hangul_J_Pieub,
	KEY_HANGUL_J_PIEUBSIOS=		XK_Hangul_J_PieubSios,
	KEY_HANGUL_J_SIOS=		XK_Hangul_J_Sios,
	KEY_HANGUL_J_SSANGSIOS=		XK_Hangul_J_SsangSios,
	KEY_HANGUL_J_IEUNG=		XK_Hangul_J_Ieung,
	KEY_HANGUL_J_JIEUJ=		XK_Hangul_J_Jieuj,
	KEY_HANGUL_J_CIEUC=		XK_Hangul_J_Cieuc,
	KEY_HANGUL_J_KHIEUQ=		XK_Hangul_J_Khieuq,
	KEY_HANGUL_J_TIEUT=		XK_Hangul_J_Tieut,
	KEY_HANGUL_J_PHIEUF=		XK_Hangul_J_Phieuf,
	KEY_HANGUL_J_HIEUH=		XK_Hangul_J_Hieuh,
	KEY_HANGUL_RIEULYEORINHIEUH=		XK_Hangul_RieulYeorinHieuh,
	KEY_HANGUL_SUNKYEONGEUMMIEUM=		XK_Hangul_SunkyeongeumMieum,
	KEY_HANGUL_SUNKYEONGEUMPIEUB=		XK_Hangul_SunkyeongeumPieub,
	KEY_HANGUL_PANSIOS=		XK_Hangul_PanSios,
	KEY_HANGUL_KKOGJIDALRINIEUNG=		XK_Hangul_KkogjiDalrinIeung,
	KEY_HANGUL_SUNKYEONGEUMPHIEUF=		XK_Hangul_SunkyeongeumPhieuf,
	KEY_HANGUL_YEORINHIEUH=		XK_Hangul_YeorinHieuh,
	KEY_HANGUL_ARAEA=		XK_Hangul_AraeA,
	KEY_HANGUL_ARAEAE=		XK_Hangul_AraeAE,
	KEY_HANGUL_J_PANSIOS=		XK_Hangul_J_PanSios,
	KEY_HANGUL_J_KKOGJIDALRINIEUNG=		XK_Hangul_J_KkogjiDalrinIeung,
	KEY_HANGUL_J_YEORINHIEUH=		XK_Hangul_J_YeorinHieuh,
	KEY_KOREAN_WON=		XK_Korean_Won,
	#endif
	#ifdef XK_LATIN1
	KEY_SPACE=		XK_space,
	KEY_EXCLAM=		XK_exclam,
	KEY_QUOTEDBL=		XK_quotedbl,
	KEY_NUMBERSIGN=		XK_numbersign,
	KEY_DOLLAR=		XK_dollar,
	KEY_PERCENT=		XK_percent,
	KEY_AMPERSAND=		XK_ampersand,
	KEY_APOSTROPHE=		XK_apostrophe,
	KEY_PARENLEFT=		XK_parenleft,
	KEY_PARENRIGHT=		XK_parenright,
	KEY_ASTERISK=		XK_asterisk,
	KEY_PLUS=		XK_plus,
	KEY_COMMA=		XK_comma,
	KEY_MINUS=		XK_minus,
	KEY_PERIOD=		XK_period,
	KEY_SLASH=		XK_slash,
	KEY_COLON=		XK_colon,
	KEY_SEMICOLON=		XK_semicolon,
	KEY_LESS=		XK_less,
	KEY_EQUAL=		XK_equal,
	KEY_GREATER=		XK_greater,
	KEY_QUESTION=		XK_question,
	KEY_AT=		XK_at,
	KEY_BRACKETLEFT=		XK_bracketleft,
	KEY_BACKSLASH=		XK_backslash,
	KEY_BRACKETRIGHT=		XK_bracketright,
	KEY_ASCIICIRCUM=		XK_asciicircum,
	KEY_UNDERSCORE=		XK_underscore,
	KEY_GRAVE=		XK_grave,
	KEY_BRACELEFT=		XK_braceleft,
	KEY_BAR=		XK_bar,
	KEY_BRACERIGHT=		XK_braceright,
	KEY_ASCIITILDE=		XK_asciitilde,
	KEY_NOBREAKSPACE=		XK_nobreakspace,
	KEY_EXCLAMDOWN=		XK_exclamdown,
	KEY_CENT=		XK_cent,
	KEY_STERLING=		XK_sterling,
	KEY_CURRENCY=		XK_currency,
	KEY_YEN=		XK_yen,
	KEY_BROKENBAR=		XK_brokenbar,
	KEY_SECTION=		XK_section,
	KEY_DIAERESIS=		XK_diaeresis,
	KEY_COPYRIGHT=		XK_copyright,
	KEY_ORDFEMININE=		XK_ordfeminine,
	KEY_GUILLEMOTLEFT=		XK_guillemotleft,
	KEY_NOTSIGN=		XK_notsign,
	KEY_HYPHEN=		XK_hyphen,
	KEY_REGISTERED=		XK_registered,
	KEY_MACRON=		XK_macron,
	KEY_DEGREE=		XK_degree,
	KEY_PLUSMINUS=		XK_plusminus,
	KEY_TWOSUPERIOR=		XK_twosuperior,
	KEY_THREESUPERIOR=		XK_threesuperior,
	KEY_ACUTE=		XK_acute,
	KEY_MU=		XK_mu,
	KEY_PARAGRAPH=		XK_paragraph,
	KEY_PERIODCENTERED=		XK_periodcentered,
	KEY_CEDILLA=		XK_cedilla,
	KEY_ONESUPERIOR=		XK_onesuperior,
	KEY_MASCULINE=		XK_masculine,
	KEY_GUILLEMOTRIGHT=		XK_guillemotright,
	KEY_ONEQUARTER=		XK_onequarter,
	KEY_ONEHALF=		XK_onehalf,
	KEY_THREEQUARTERS=		XK_threequarters,
	KEY_QUESTIONDOWN=		XK_questiondown,
	KEY_AGRAVE=		XK_Agrave,
	KEY_AACUTE=		XK_Aacute,
	KEY_ACIRCUMFLEX=		XK_Acircumflex,
	KEY_ATILDE=		XK_Atilde,
	KEY_ADIAERESIS=		XK_Adiaeresis,
	KEY_ARING=		XK_Aring,
	KEY_AE=		XK_AE,
	KEY_CCEDILLA=		XK_Ccedilla,
	KEY_EGRAVE=		XK_Egrave,
	KEY_EACUTE=		XK_Eacute,
	KEY_ECIRCUMFLEX=		XK_Ecircumflex,
	KEY_EDIAERESIS=		XK_Ediaeresis,
	KEY_IGRAVE=		XK_Igrave,
	KEY_IACUTE=		XK_Iacute,
	KEY_ICIRCUMFLEX=		XK_Icircumflex,
	KEY_IDIAERESIS=		XK_Idiaeresis,
	KEY_NTILDE=		XK_Ntilde,
	KEY_OGRAVE=		XK_Ograve,
	KEY_OACUTE=		XK_Oacute,
	KEY_OCIRCUMFLEX=		XK_Ocircumflex,
	KEY_OTILDE=		XK_Otilde,
	KEY_ODIAERESIS=		XK_Odiaeresis,
	KEY_MULTIPLY=		XK_multiply,
	KEY_OSLASH=		XK_Oslash,
	KEY_OOBLIQUE=		XK_Ooblique,
	KEY_UGRAVE=		XK_Ugrave,
	KEY_UACUTE=		XK_Uacute,
	KEY_UCIRCUMFLEX=		XK_Ucircumflex,
	KEY_UDIAERESIS=		XK_Udiaeresis,
	KEY_YACUTE=		XK_Yacute,
	KEY_SSHARP=		XK_ssharp,
	KEY_ETH=		XK_eth,
	KEY_DIVISION=		XK_division,
	KEY_THORN=		XK_thorn,
	KEY_YDIAERESIS=		XK_ydiaeresis,
	#endif
	#ifdef XK_LATIN2
	KEY_AOGONEK=		XK_Aogonek,
	KEY_BREVE=		XK_breve,
	KEY_LSTROKE=		XK_Lstroke,
	KEY_LCARON=		XK_Lcaron,
	KEY_SACUTE=		XK_Sacute,
	KEY_SCARON=		XK_Scaron,
	KEY_SCEDILLA=		XK_Scedilla,
	KEY_TCARON=		XK_Tcaron,
	KEY_ZACUTE=		XK_Zacute,
	KEY_ZCARON=		XK_Zcaron,
	KEY_ZABOVEDOT=		XK_Zabovedot,
	KEY_OGONEK=		XK_ogonek,
	KEY_CARON=		XK_caron,
	KEY_DOUBLEACUTE=		XK_doubleacute,
	KEY_RACUTE=		XK_Racute,
	KEY_ABREVE=		XK_Abreve,
	KEY_LACUTE=		XK_Lacute,
	KEY_CACUTE=		XK_Cacute,
	KEY_CCARON=		XK_Ccaron,
	KEY_EOGONEK=		XK_Eogonek,
	KEY_ECARON=		XK_Ecaron,
	KEY_DCARON=		XK_Dcaron,
	KEY_DSTROKE=		XK_Dstroke,
	KEY_NACUTE=		XK_Nacute,
	KEY_NCARON=		XK_Ncaron,
	KEY_ODOUBLEACUTE=		XK_Odoubleacute,
	KEY_RCARON=		XK_Rcaron,
	KEY_URING=		XK_Uring,
	KEY_UDOUBLEACUTE=		XK_Udoubleacute,
	KEY_TCEDILLA=		XK_Tcedilla,
	KEY_ABOVEDOT=		XK_abovedot,
	#endif
	#ifdef XK_LATIN3
	KEY_HSTROKE=		XK_Hstroke,
	KEY_HCIRCUMFLEX=		XK_Hcircumflex,
	KEY_IABOVEDOT=		XK_Iabovedot,
	KEY_GBREVE=		XK_Gbreve,
	KEY_JCIRCUMFLEX=		XK_Jcircumflex,
	KEY_IDOTLESS=		XK_idotless,
	KEY_CABOVEDOT=		XK_Cabovedot,
	KEY_CCIRCUMFLEX=		XK_Ccircumflex,
	KEY_GABOVEDOT=		XK_Gabovedot,
	KEY_GCIRCUMFLEX=		XK_Gcircumflex,
	KEY_UBREVE=		XK_Ubreve,
	KEY_SCIRCUMFLEX=		XK_Scircumflex,
	#endif
	#ifdef XK_LATIN4
	KEY_KRA=		XK_kra,
	KEY_RCEDILLA=		XK_Rcedilla,
	KEY_ITILDE=		XK_Itilde,
	KEY_LCEDILLA=		XK_Lcedilla,
	KEY_EMACRON=		XK_Emacron,
	KEY_GCEDILLA=		XK_Gcedilla,
	KEY_TSLASH=		XK_Tslash,
	KEY_ENG=		XK_ENG,
	KEY_AMACRON=		XK_Amacron,
	KEY_IOGONEK=		XK_Iogonek,
	KEY_EABOVEDOT=		XK_Eabovedot,
	KEY_IMACRON=		XK_Imacron,
	KEY_NCEDILLA=		XK_Ncedilla,
	KEY_OMACRON=		XK_Omacron,
	KEY_KCEDILLA=		XK_Kcedilla,
	KEY_UOGONEK=		XK_Uogonek,
	KEY_UTILDE=		XK_Utilde,
	KEY_UMACRON=		XK_Umacron,
	#endif
	#ifdef XK_LATIN8
	KEY_WCIRCUMFLEX=		XK_Wcircumflex,
	KEY_YCIRCUMFLEX=		XK_Ycircumflex,
	KEY_BABOVEDOT=		XK_Babovedot,
	KEY_DABOVEDOT=		XK_Dabovedot,
	KEY_FABOVEDOT=		XK_Fabovedot,
	KEY_MABOVEDOT=		XK_Mabovedot,
	KEY_PABOVEDOT=		XK_Pabovedot,
	KEY_SABOVEDOT=		XK_Sabovedot,
	KEY_TABOVEDOT=		XK_Tabovedot,
	KEY_WGRAVE=		XK_Wgrave,
	KEY_WACUTE=		XK_Wacute,
	KEY_WDIAERESIS=		XK_Wdiaeresis,
	KEY_YGRAVE=		XK_Ygrave,
	#endif
	#ifdef XK_LATIN9
	KEY_OE=		XK_OE,
	#endif
	#ifdef XK_MATHEMATICAL
	KEY_ZEROSUPERIOR=		XK_zerosuperior,
	KEY_FOURSUPERIOR=		XK_foursuperior,
	KEY_FIVESUPERIOR=		XK_fivesuperior,
	KEY_SIXSUPERIOR=		XK_sixsuperior,
	KEY_SEVENSUPERIOR=		XK_sevensuperior,
	KEY_EIGHTSUPERIOR=		XK_eightsuperior,
	KEY_NINESUPERIOR=		XK_ninesuperior,
	KEY_ZEROSUBSCRIPT=		XK_zerosubscript,
	KEY_ONESUBSCRIPT=		XK_onesubscript,
	KEY_TWOSUBSCRIPT=		XK_twosubscript,
	KEY_THREESUBSCRIPT=		XK_threesubscript,
	KEY_FOURSUBSCRIPT=		XK_foursubscript,
	KEY_FIVESUBSCRIPT=		XK_fivesubscript,
	KEY_SIXSUBSCRIPT=		XK_sixsubscript,
	KEY_SEVENSUBSCRIPT=		XK_sevensubscript,
	KEY_EIGHTSUBSCRIPT=		XK_eightsubscript,
	KEY_NINESUBSCRIPT=		XK_ninesubscript,
	KEY_PARTDIFFERENTIAL=		XK_partdifferential,
	KEY_EMPTYSET=		XK_emptyset,
	KEY_ELEMENTOF=		XK_elementof,
	KEY_NOTELEMENTOF=		XK_notelementof,
	KEY_CONTAINSAS=		XK_containsas,
	KEY_SQUAREROOT=		XK_squareroot,
	KEY_CUBEROOT=		XK_cuberoot,
	KEY_FOURTHROOT=		XK_fourthroot,
	KEY_DINTEGRAL=		XK_dintegral,
	KEY_TINTEGRAL=		XK_tintegral,
	KEY_BECAUSE=		XK_because,
	KEY_APPROXEQ=		XK_approxeq,
	KEY_NOTAPPROXEQ=		XK_notapproxeq,
	KEY_NOTIDENTICAL=		XK_notidentical,
	KEY_STRICTEQ=		XK_stricteq,
	#endif
	#ifdef XK_MISCELLANY
	KEY_BACKSPACE=		XK_BackSpace,
	KEY_TAB=		XK_Tab,
	KEY_LINEFEED=		XK_Linefeed,
	KEY_CLEAR=		XK_Clear,
	KEY_RETURN=		XK_Return,
	KEY_PAUSE=		XK_Pause,
	KEY_SCROLL_LOCK=		XK_Scroll_Lock,
	KEY_SYS_REQ=		XK_Sys_Req,
	KEY_ESCAPE=		XK_Escape,
	KEY_DELETE=		XK_Delete,
	KEY_MULTI_KEY=		XK_Multi_key,
	KEY_CODEINPUT=		XK_Codeinput,
	KEY_SINGLECANDIDATE=		XK_SingleCandidate,
	KEY_MULTIPLECANDIDATE=		XK_MultipleCandidate,
	KEY_PREVIOUSCANDIDATE=		XK_PreviousCandidate,
	KEY_KANJI=		XK_Kanji,
	KEY_MUHENKAN=		XK_Muhenkan,
	KEY_HENKAN_MODE=		XK_Henkan_Mode,
	KEY_HENKAN=		XK_Henkan,
	KEY_ROMAJI=		XK_Romaji,
	KEY_HIRAGANA=		XK_Hiragana,
	KEY_KATAKANA=		XK_Katakana,
	KEY_HIRAGANA_KATAKANA=		XK_Hiragana_Katakana,
	KEY_ZENKAKU=		XK_Zenkaku,
	KEY_HANKAKU=		XK_Hankaku,
	KEY_ZENKAKU_HANKAKU=		XK_Zenkaku_Hankaku,
	KEY_TOUROKU=		XK_Touroku,
	KEY_MASSYO=		XK_Massyo,
	KEY_KANA_LOCK=		XK_Kana_Lock,
	KEY_KANA_SHIFT=		XK_Kana_Shift,
	KEY_EISU_SHIFT=		XK_Eisu_Shift,
	KEY_EISU_TOGGLE=		XK_Eisu_toggle,
	KEY_KANJI_BANGOU=		XK_Kanji_Bangou,
	KEY_ZEN_KOHO=		XK_Zen_Koho,
	KEY_MAE_KOHO=		XK_Mae_Koho,
	KEY_HOME=		XK_Home,
	KEY_LEFT=		XK_Left,
	KEY_UP=		XK_Up,
	KEY_RIGHT=		XK_Right,
	KEY_DOWN=		XK_Down,
	KEY_PRIOR=		XK_Prior,
	KEY_PAGE_UP=		XK_Page_Up,
	KEY_NEXT=		XK_Next,
	KEY_PAGE_DOWN=		XK_Page_Down,
	KEY_END=		XK_End,
	KEY_BEGIN=		XK_Begin,
	KEY_SELECT=		XK_Select,
	KEY_PRINT=		XK_Print,
	KEY_EXECUTE=		XK_Execute,
	KEY_INSERT=		XK_Insert,
	KEY_UNDO=		XK_Undo,
	KEY_REDO=		XK_Redo,
	KEY_MENU=		XK_Menu,
	KEY_FIND=		XK_Find,
	KEY_CANCEL=		XK_Cancel,
	KEY_HELP=		XK_Help,
	KEY_BREAK=		XK_Break,
	KEY_MODE_SWITCH=		XK_Mode_switch,
	KEY_SCRIPT_SWITCH=		XK_script_switch,
	KEY_NUM_LOCK=		XK_Num_Lock,
	KEY_KP_SPACE=		XK_KP_Space,
	KEY_KP_TAB=		XK_KP_Tab,
	KEY_KP_ENTER=		XK_KP_Enter,
	KEY_KP_F1=		XK_KP_F1,
	KEY_KP_F2=		XK_KP_F2,
	KEY_KP_F3=		XK_KP_F3,
	KEY_KP_F4=		XK_KP_F4,
	KEY_KP_HOME=		XK_KP_Home,
	KEY_KP_LEFT=		XK_KP_Left,
	KEY_KP_UP=		XK_KP_Up,
	KEY_KP_RIGHT=		XK_KP_Right,
	KEY_KP_DOWN=		XK_KP_Down,
	KEY_KP_PRIOR=		XK_KP_Prior,
	KEY_KP_PAGE_UP=		XK_KP_Page_Up,
	KEY_KP_NEXT=		XK_KP_Next,
	KEY_KP_PAGE_DOWN=		XK_KP_Page_Down,
	KEY_KP_END=		XK_KP_End,
	KEY_KP_BEGIN=		XK_KP_Begin,
	KEY_KP_INSERT=		XK_KP_Insert,
	KEY_KP_DELETE=		XK_KP_Delete,
	KEY_KP_EQUAL=		XK_KP_Equal,
	KEY_KP_MULTIPLY=		XK_KP_Multiply,
	KEY_KP_ADD=		XK_KP_Add,
	KEY_KP_SEPARATOR=		XK_KP_Separator,
	KEY_KP_SUBTRACT=		XK_KP_Subtract,
	KEY_KP_DECIMAL=		XK_KP_Decimal,
	KEY_KP_DIVIDE=		XK_KP_Divide,
	KEY_KP_0=		XK_KP_0,
	KEY_KP_1=		XK_KP_1,
	KEY_KP_2=		XK_KP_2,
	KEY_KP_3=		XK_KP_3,
	KEY_KP_4=		XK_KP_4,
	KEY_KP_5=		XK_KP_5,
	KEY_KP_6=		XK_KP_6,
	KEY_KP_7=		XK_KP_7,
	KEY_KP_8=		XK_KP_8,
	KEY_KP_9=		XK_KP_9,
	KEY_F1=		XK_F1,
	KEY_F2=		XK_F2,
	KEY_F3=		XK_F3,
	KEY_F4=		XK_F4,
	KEY_F5=		XK_F5,
	KEY_F6=		XK_F6,
	KEY_F7=		XK_F7,
	KEY_F8=		XK_F8,
	KEY_F9=		XK_F9,
	KEY_F10=		XK_F10,
	KEY_F11=		XK_F11,
	KEY_L1=		XK_L1,
	KEY_F12=		XK_F12,
	KEY_L2=		XK_L2,
	KEY_F13=		XK_F13,
	KEY_L3=		XK_L3,
	KEY_F14=		XK_F14,
	KEY_L4=		XK_L4,
	KEY_F15=		XK_F15,
	KEY_L5=		XK_L5,
	KEY_F16=		XK_F16,
	KEY_L6=		XK_L6,
	KEY_F17=		XK_F17,
	KEY_L7=		XK_L7,
	KEY_F18=		XK_F18,
	KEY_L8=		XK_L8,
	KEY_F19=		XK_F19,
	KEY_L9=		XK_L9,
	KEY_F20=		XK_F20,
	KEY_L10=		XK_L10,
	KEY_F21=		XK_F21,
	KEY_R1=		XK_R1,
	KEY_F22=		XK_F22,
	KEY_R2=		XK_R2,
	KEY_F23=		XK_F23,
	KEY_R3=		XK_R3,
	KEY_F24=		XK_F24,
	KEY_R4=		XK_R4,
	KEY_F25=		XK_F25,
	KEY_R5=		XK_R5,
	KEY_F26=		XK_F26,
	KEY_R6=		XK_R6,
	KEY_F27=		XK_F27,
	KEY_R7=		XK_R7,
	KEY_F28=		XK_F28,
	KEY_R8=		XK_R8,
	KEY_F29=		XK_F29,
	KEY_R9=		XK_R9,
	KEY_F30=		XK_F30,
	KEY_R10=		XK_R10,
	KEY_F31=		XK_F31,
	KEY_R11=		XK_R11,
	KEY_F32=		XK_F32,
	KEY_R12=		XK_R12,
	KEY_F33=		XK_F33,
	KEY_R13=		XK_R13,
	KEY_F34=		XK_F34,
	KEY_R14=		XK_R14,
	KEY_F35=		XK_F35,
	KEY_R15=		XK_R15,
	KEY_SHIFT_L=		XK_Shift_L,
	KEY_SHIFT_R=		XK_Shift_R,
	KEY_CONTROL_L=		XK_Control_L,
	KEY_CONTROL_R=		XK_Control_R,
	KEY_CAPS_LOCK=		XK_Caps_Lock,
	KEY_SHIFT_LOCK=		XK_Shift_Lock,
	KEY_META_L=		XK_Meta_L,
	KEY_META_R=		XK_Meta_R,
	KEY_ALT_L=		XK_Alt_L,
	KEY_ALT_R=		XK_Alt_R,
	KEY_SUPER_L=		XK_Super_L,
	KEY_SUPER_R=		XK_Super_R,
	KEY_HYPER_L=		XK_Hyper_L,
	KEY_HYPER_R=		XK_Hyper_R,
	#endif
	#ifdef XK_PUBLISHING
	KEY_EMSPACE=		XK_emspace,
	KEY_ENSPACE=		XK_enspace,
	KEY_EM3SPACE=		XK_em3space,
	KEY_EM4SPACE=		XK_em4space,
	KEY_DIGITSPACE=		XK_digitspace,
	KEY_PUNCTSPACE=		XK_punctspace,
	KEY_THINSPACE=		XK_thinspace,
	KEY_HAIRSPACE=		XK_hairspace,
	KEY_EMDASH=		XK_emdash,
	KEY_ENDASH=		XK_endash,
	KEY_SIGNIFBLANK=		XK_signifblank,
	KEY_ELLIPSIS=		XK_ellipsis,
	KEY_DOUBBASELINEDOT=		XK_doubbaselinedot,
	KEY_ONETHIRD=		XK_onethird,
	KEY_TWOTHIRDS=		XK_twothirds,
	KEY_ONEFIFTH=		XK_onefifth,
	KEY_TWOFIFTHS=		XK_twofifths,
	KEY_THREEFIFTHS=		XK_threefifths,
	KEY_FOURFIFTHS=		XK_fourfifths,
	KEY_ONESIXTH=		XK_onesixth,
	KEY_FIVESIXTHS=		XK_fivesixths,
	KEY_CAREOF=		XK_careof,
	KEY_FIGDASH=		XK_figdash,
	KEY_LEFTANGLEBRACKET=		XK_leftanglebracket,
	KEY_DECIMALPOINT=		XK_decimalpoint,
	KEY_RIGHTANGLEBRACKET=		XK_rightanglebracket,
	KEY_MARKER=		XK_marker,
	KEY_ONEEIGHTH=		XK_oneeighth,
	KEY_THREEEIGHTHS=		XK_threeeighths,
	KEY_FIVEEIGHTHS=		XK_fiveeighths,
	KEY_SEVENEIGHTHS=		XK_seveneighths,
	KEY_TRADEMARK=		XK_trademark,
	KEY_SIGNATUREMARK=		XK_signaturemark,
	KEY_TRADEMARKINCIRCLE=		XK_trademarkincircle,
	KEY_LEFTOPENTRIANGLE=		XK_leftopentriangle,
	KEY_RIGHTOPENTRIANGLE=		XK_rightopentriangle,
	KEY_EMOPENCIRCLE=		XK_emopencircle,
	KEY_EMOPENRECTANGLE=		XK_emopenrectangle,
	KEY_LEFTSINGLEQUOTEMARK=		XK_leftsinglequotemark,
	KEY_RIGHTSINGLEQUOTEMARK=		XK_rightsinglequotemark,
	KEY_LEFTDOUBLEQUOTEMARK=		XK_leftdoublequotemark,
	KEY_RIGHTDOUBLEQUOTEMARK=		XK_rightdoublequotemark,
	KEY_PRESCRIPTION=		XK_prescription,
	KEY_PERMILLE=		XK_permille,
	KEY_MINUTES=		XK_minutes,
	KEY_SECONDS=		XK_seconds,
	KEY_LATINCROSS=		XK_latincross,
	KEY_HEXAGRAM=		XK_hexagram,
	KEY_FILLEDRECTBULLET=		XK_filledrectbullet,
	KEY_FILLEDLEFTTRIBULLET=		XK_filledlefttribullet,
	KEY_FILLEDRIGHTTRIBULLET=		XK_filledrighttribullet,
	KEY_EMFILLEDCIRCLE=		XK_emfilledcircle,
	KEY_EMFILLEDRECT=		XK_emfilledrect,
	KEY_ENOPENCIRCBULLET=		XK_enopencircbullet,
	KEY_ENOPENSQUAREBULLET=		XK_enopensquarebullet,
	KEY_OPENRECTBULLET=		XK_openrectbullet,
	KEY_OPENTRIBULLETUP=		XK_opentribulletup,
	KEY_OPENTRIBULLETDOWN=		XK_opentribulletdown,
	KEY_OPENSTAR=		XK_openstar,
	KEY_ENFILLEDCIRCBULLET=		XK_enfilledcircbullet,
	KEY_ENFILLEDSQBULLET=		XK_enfilledsqbullet,
	KEY_FILLEDTRIBULLETUP=		XK_filledtribulletup,
	KEY_FILLEDTRIBULLETDOWN=		XK_filledtribulletdown,
	KEY_LEFTPOINTER=		XK_leftpointer,
	KEY_RIGHTPOINTER=		XK_rightpointer,
	KEY_CLUB=		XK_club,
	KEY_DIAMOND=		XK_diamond,
	KEY_HEART=		XK_heart,
	KEY_MALTESECROSS=		XK_maltesecross,
	KEY_DAGGER=		XK_dagger,
	KEY_DOUBLEDAGGER=		XK_doubledagger,
	KEY_CHECKMARK=		XK_checkmark,
	KEY_BALLOTCROSS=		XK_ballotcross,
	KEY_MUSICALSHARP=		XK_musicalsharp,
	KEY_MUSICALFLAT=		XK_musicalflat,
	KEY_MALESYMBOL=		XK_malesymbol,
	KEY_FEMALESYMBOL=		XK_femalesymbol,
	KEY_TELEPHONE=		XK_telephone,
	KEY_TELEPHONERECORDER=		XK_telephonerecorder,
	KEY_PHONOGRAPHCOPYRIGHT=		XK_phonographcopyright,
	KEY_CARET=		XK_caret,
	KEY_SINGLELOWQUOTEMARK=		XK_singlelowquotemark,
	KEY_DOUBLELOWQUOTEMARK=		XK_doublelowquotemark,
	KEY_CURSOR=		XK_cursor,
	#endif
	#ifdef XK_SINHALA
	KEY_SINH_NG=		XK_Sinh_ng,
	KEY_SINH_H2=		XK_Sinh_h2,
	KEY_SINH_A=		XK_Sinh_a,
	KEY_SINH_AA=		XK_Sinh_aa,
	KEY_SINH_AE=		XK_Sinh_ae,
	KEY_SINH_AEE=		XK_Sinh_aee,
	KEY_SINH_I=		XK_Sinh_i,
	KEY_SINH_II=		XK_Sinh_ii,
	KEY_SINH_U=		XK_Sinh_u,
	KEY_SINH_UU=		XK_Sinh_uu,
	KEY_SINH_RI=		XK_Sinh_ri,
	KEY_SINH_RII=		XK_Sinh_rii,
	KEY_SINH_LU=		XK_Sinh_lu,
	KEY_SINH_LUU=		XK_Sinh_luu,
	KEY_SINH_E=		XK_Sinh_e,
	KEY_SINH_EE=		XK_Sinh_ee,
	KEY_SINH_AI=		XK_Sinh_ai,
	KEY_SINH_O=		XK_Sinh_o,
	KEY_SINH_OO=		XK_Sinh_oo,
	KEY_SINH_AU=		XK_Sinh_au,
	KEY_SINH_KA=		XK_Sinh_ka,
	KEY_SINH_KHA=		XK_Sinh_kha,
	KEY_SINH_GA=		XK_Sinh_ga,
	KEY_SINH_GHA=		XK_Sinh_gha,
	KEY_SINH_NG2=		XK_Sinh_ng2,
	KEY_SINH_NGA=		XK_Sinh_nga,
	KEY_SINH_CA=		XK_Sinh_ca,
	KEY_SINH_CHA=		XK_Sinh_cha,
	KEY_SINH_JA=		XK_Sinh_ja,
	KEY_SINH_JHA=		XK_Sinh_jha,
	KEY_SINH_NYA=		XK_Sinh_nya,
	KEY_SINH_JNYA=		XK_Sinh_jnya,
	KEY_SINH_NJA=		XK_Sinh_nja,
	KEY_SINH_TTA=		XK_Sinh_tta,
	KEY_SINH_TTHA=		XK_Sinh_ttha,
	KEY_SINH_DDA=		XK_Sinh_dda,
	KEY_SINH_DDHA=		XK_Sinh_ddha,
	KEY_SINH_NNA=		XK_Sinh_nna,
	KEY_SINH_NDDA=		XK_Sinh_ndda,
	KEY_SINH_THA=		XK_Sinh_tha,
	KEY_SINH_THHA=		XK_Sinh_thha,
	KEY_SINH_DHA=		XK_Sinh_dha,
	KEY_SINH_DHHA=		XK_Sinh_dhha,
	KEY_SINH_NA=		XK_Sinh_na,
	KEY_SINH_NDHA=		XK_Sinh_ndha,
	KEY_SINH_PA=		XK_Sinh_pa,
	KEY_SINH_PHA=		XK_Sinh_pha,
	KEY_SINH_BA=		XK_Sinh_ba,
	KEY_SINH_BHA=		XK_Sinh_bha,
	KEY_SINH_MA=		XK_Sinh_ma,
	KEY_SINH_MBA=		XK_Sinh_mba,
	KEY_SINH_YA=		XK_Sinh_ya,
	KEY_SINH_RA=		XK_Sinh_ra,
	KEY_SINH_LA=		XK_Sinh_la,
	KEY_SINH_VA=		XK_Sinh_va,
	KEY_SINH_SHA=		XK_Sinh_sha,
	KEY_SINH_SSHA=		XK_Sinh_ssha,
	KEY_SINH_SA=		XK_Sinh_sa,
	KEY_SINH_HA=		XK_Sinh_ha,
	KEY_SINH_LLA=		XK_Sinh_lla,
	KEY_SINH_FA=		XK_Sinh_fa,
	KEY_SINH_AL=		XK_Sinh_al,
	KEY_SINH_AA2=		XK_Sinh_aa2,
	KEY_SINH_AE2=		XK_Sinh_ae2,
	KEY_SINH_AEE2=		XK_Sinh_aee2,
	KEY_SINH_I2=		XK_Sinh_i2,
	KEY_SINH_II2=		XK_Sinh_ii2,
	KEY_SINH_U2=		XK_Sinh_u2,
	KEY_SINH_UU2=		XK_Sinh_uu2,
	KEY_SINH_RU2=		XK_Sinh_ru2,
	KEY_SINH_E2=		XK_Sinh_e2,
	KEY_SINH_EE2=		XK_Sinh_ee2,
	KEY_SINH_AI2=		XK_Sinh_ai2,
	KEY_SINH_O2=		XK_Sinh_o2,
	KEY_SINH_OO2=		XK_Sinh_oo2,
	KEY_SINH_AU2=		XK_Sinh_au2,
	KEY_SINH_LU2=		XK_Sinh_lu2,
	KEY_SINH_RUU2=		XK_Sinh_ruu2,
	KEY_SINH_LUU2=		XK_Sinh_luu2,
	KEY_SINH_KUNDDALIYA=		XK_Sinh_kunddaliya,
	#endif
	#ifdef XK_SPECIAL
	KEY_BLANK=		XK_blank,
	KEY_SOLIDDIAMOND=		XK_soliddiamond,
	KEY_CHECKERBOARD=		XK_checkerboard,
	KEY_HT=		XK_ht,
	KEY_FF=		XK_ff,
	KEY_CR=		XK_cr,
	KEY_LF=		XK_lf,
	KEY_NL=		XK_nl,
	KEY_VT=		XK_vt,
	KEY_LOWRIGHTCORNER=		XK_lowrightcorner,
	KEY_UPRIGHTCORNER=		XK_uprightcorner,
	KEY_UPLEFTCORNER=		XK_upleftcorner,
	KEY_LOWLEFTCORNER=		XK_lowleftcorner,
	KEY_CROSSINGLINES=		XK_crossinglines,
	KEY_HORIZLINESCAN1=		XK_horizlinescan1,
	KEY_HORIZLINESCAN3=		XK_horizlinescan3,
	KEY_HORIZLINESCAN5=		XK_horizlinescan5,
	KEY_HORIZLINESCAN7=		XK_horizlinescan7,
	KEY_HORIZLINESCAN9=		XK_horizlinescan9,
	KEY_LEFTT=		XK_leftt,
	KEY_RIGHTT=		XK_rightt,
	KEY_BOTT=		XK_bott,
	KEY_TOPT=		XK_topt,
	KEY_VERTBAR=		XK_vertbar,
	#endif
	#ifdef XK_TECHNICAL
	KEY_LEFTRADICAL=		XK_leftradical,
	KEY_TOPLEFTRADICAL=		XK_topleftradical,
	KEY_HORIZCONNECTOR=		XK_horizconnector,
	KEY_TOPINTEGRAL=		XK_topintegral,
	KEY_BOTINTEGRAL=		XK_botintegral,
	KEY_VERTCONNECTOR=		XK_vertconnector,
	KEY_TOPLEFTSQBRACKET=		XK_topleftsqbracket,
	KEY_BOTLEFTSQBRACKET=		XK_botleftsqbracket,
	KEY_TOPRIGHTSQBRACKET=		XK_toprightsqbracket,
	KEY_BOTRIGHTSQBRACKET=		XK_botrightsqbracket,
	KEY_TOPLEFTPARENS=		XK_topleftparens,
	KEY_BOTLEFTPARENS=		XK_botleftparens,
	KEY_TOPRIGHTPARENS=		XK_toprightparens,
	KEY_BOTRIGHTPARENS=		XK_botrightparens,
	KEY_LEFTMIDDLECURLYBRACE=		XK_leftmiddlecurlybrace,
	KEY_RIGHTMIDDLECURLYBRACE=		XK_rightmiddlecurlybrace,
	KEY_TOPLEFTSUMMATION=		XK_topleftsummation,
	KEY_BOTLEFTSUMMATION=		XK_botleftsummation,
	KEY_TOPVERTSUMMATIONCONNECTOR=		XK_topvertsummationconnector,
	KEY_BOTVERTSUMMATIONCONNECTOR=		XK_botvertsummationconnector,
	KEY_TOPRIGHTSUMMATION=		XK_toprightsummation,
	KEY_BOTRIGHTSUMMATION=		XK_botrightsummation,
	KEY_RIGHTMIDDLESUMMATION=		XK_rightmiddlesummation,
	KEY_LESSTHANEQUAL=		XK_lessthanequal,
	KEY_NOTEQUAL=		XK_notequal,
	KEY_GREATERTHANEQUAL=		XK_greaterthanequal,
	KEY_INTEGRAL=		XK_integral,
	KEY_THEREFORE=		XK_therefore,
	KEY_VARIATION=		XK_variation,
	KEY_INFINITY=		XK_infinity,
	KEY_NABLA=		XK_nabla,
	KEY_APPROXIMATE=		XK_approximate,
	KEY_SIMILAREQUAL=		XK_similarequal,
	KEY_IFONLYIF=		XK_ifonlyif,
	KEY_IMPLIES=		XK_implies,
	KEY_IDENTICAL=		XK_identical,
	KEY_RADICAL=		XK_radical,
	KEY_INCLUDEDIN=		XK_includedin,
	KEY_INCLUDES=		XK_includes,
	KEY_INTERSECTION=		XK_intersection,
	KEY_UNION=		XK_union,
	KEY_LOGICALAND=		XK_logicaland,
	KEY_LOGICALOR=		XK_logicalor,
	KEY_PARTIALDERIVATIVE=		XK_partialderivative,
	KEY_FUNCTION=		XK_function,
	KEY_LEFTARROW=		XK_leftarrow,
	KEY_UPARROW=		XK_uparrow,
	KEY_RIGHTARROW=		XK_rightarrow,
	KEY_DOWNARROW=		XK_downarrow,
	#endif
	#ifdef XK_THAI
	KEY_THAI_KOKAI=		XK_Thai_kokai,
	KEY_THAI_KHOKHAI=		XK_Thai_khokhai,
	KEY_THAI_KHOKHUAT=		XK_Thai_khokhuat,
	KEY_THAI_KHOKHWAI=		XK_Thai_khokhwai,
	KEY_THAI_KHOKHON=		XK_Thai_khokhon,
	KEY_THAI_KHORAKHANG=		XK_Thai_khorakhang,
	KEY_THAI_NGONGU=		XK_Thai_ngongu,
	KEY_THAI_CHOCHAN=		XK_Thai_chochan,
	KEY_THAI_CHOCHING=		XK_Thai_choching,
	KEY_THAI_CHOCHANG=		XK_Thai_chochang,
	KEY_THAI_SOSO=		XK_Thai_soso,
	KEY_THAI_CHOCHOE=		XK_Thai_chochoe,
	KEY_THAI_YOYING=		XK_Thai_yoying,
	KEY_THAI_DOCHADA=		XK_Thai_dochada,
	KEY_THAI_TOPATAK=		XK_Thai_topatak,
	KEY_THAI_THOTHAN=		XK_Thai_thothan,
	KEY_THAI_THONANGMONTHO=		XK_Thai_thonangmontho,
	KEY_THAI_THOPHUTHAO=		XK_Thai_thophuthao,
	KEY_THAI_NONEN=		XK_Thai_nonen,
	KEY_THAI_DODEK=		XK_Thai_dodek,
	KEY_THAI_TOTAO=		XK_Thai_totao,
	KEY_THAI_THOTHUNG=		XK_Thai_thothung,
	KEY_THAI_THOTHAHAN=		XK_Thai_thothahan,
	KEY_THAI_THOTHONG=		XK_Thai_thothong,
	KEY_THAI_NONU=		XK_Thai_nonu,
	KEY_THAI_BOBAIMAI=		XK_Thai_bobaimai,
	KEY_THAI_POPLA=		XK_Thai_popla,
	KEY_THAI_PHOPHUNG=		XK_Thai_phophung,
	KEY_THAI_FOFA=		XK_Thai_fofa,
	KEY_THAI_PHOPHAN=		XK_Thai_phophan,
	KEY_THAI_FOFAN=		XK_Thai_fofan,
	KEY_THAI_PHOSAMPHAO=		XK_Thai_phosamphao,
	KEY_THAI_MOMA=		XK_Thai_moma,
	KEY_THAI_YOYAK=		XK_Thai_yoyak,
	KEY_THAI_RORUA=		XK_Thai_rorua,
	KEY_THAI_RU=		XK_Thai_ru,
	KEY_THAI_LOLING=		XK_Thai_loling,
	KEY_THAI_LU=		XK_Thai_lu,
	KEY_THAI_WOWAEN=		XK_Thai_wowaen,
	KEY_THAI_SOSALA=		XK_Thai_sosala,
	KEY_THAI_SORUSI=		XK_Thai_sorusi,
	KEY_THAI_SOSUA=		XK_Thai_sosua,
	KEY_THAI_HOHIP=		XK_Thai_hohip,
	KEY_THAI_LOCHULA=		XK_Thai_lochula,
	KEY_THAI_OANG=		XK_Thai_oang,
	KEY_THAI_HONOKHUK=		XK_Thai_honokhuk,
	KEY_THAI_PAIYANNOI=		XK_Thai_paiyannoi,
	KEY_THAI_SARAA=		XK_Thai_saraa,
	KEY_THAI_MAIHANAKAT=		XK_Thai_maihanakat,
	KEY_THAI_SARAAA=		XK_Thai_saraaa,
	KEY_THAI_SARAAM=		XK_Thai_saraam,
	KEY_THAI_SARAI=		XK_Thai_sarai,
	KEY_THAI_SARAII=		XK_Thai_saraii,
	KEY_THAI_SARAUE=		XK_Thai_saraue,
	KEY_THAI_SARAUEE=		XK_Thai_sarauee,
	KEY_THAI_SARAU=		XK_Thai_sarau,
	KEY_THAI_SARAUU=		XK_Thai_sarauu,
	KEY_THAI_PHINTHU=		XK_Thai_phinthu,
	KEY_THAI_MAIHANAKAT_MAITHO=		XK_Thai_maihanakat_maitho,
	KEY_THAI_BAHT=		XK_Thai_baht,
	KEY_THAI_SARAE=		XK_Thai_sarae,
	KEY_THAI_SARAAE=		XK_Thai_saraae,
	KEY_THAI_SARAO=		XK_Thai_sarao,
	KEY_THAI_SARAAIMAIMUAN=		XK_Thai_saraaimaimuan,
	KEY_THAI_SARAAIMAIMALAI=		XK_Thai_saraaimaimalai,
	KEY_THAI_LAKKHANGYAO=		XK_Thai_lakkhangyao,
	KEY_THAI_MAIYAMOK=		XK_Thai_maiyamok,
	KEY_THAI_MAITAIKHU=		XK_Thai_maitaikhu,
	KEY_THAI_MAIEK=		XK_Thai_maiek,
	KEY_THAI_MAITHO=		XK_Thai_maitho,
	KEY_THAI_MAITRI=		XK_Thai_maitri,
	KEY_THAI_MAICHATTAWA=		XK_Thai_maichattawa,
	KEY_THAI_THANTHAKHAT=		XK_Thai_thanthakhat,
	KEY_THAI_NIKHAHIT=		XK_Thai_nikhahit,
	KEY_THAI_LEKSUN=		XK_Thai_leksun,
	KEY_THAI_LEKNUNG=		XK_Thai_leknung,
	KEY_THAI_LEKSONG=		XK_Thai_leksong,
	KEY_THAI_LEKSAM=		XK_Thai_leksam,
	KEY_THAI_LEKSI=		XK_Thai_leksi,
	KEY_THAI_LEKHA=		XK_Thai_lekha,
	KEY_THAI_LEKHOK=		XK_Thai_lekhok,
	KEY_THAI_LEKCHET=		XK_Thai_lekchet,
	KEY_THAI_LEKPAET=		XK_Thai_lekpaet,
	KEY_THAI_LEKKAO=		XK_Thai_lekkao,
	#endif
	#ifdef XK_VIETNAMESE
	KEY_ABELOWDOT=		XK_Abelowdot,
	KEY_AHOOK=		XK_Ahook,
	KEY_ACIRCUMFLEXACUTE=		XK_Acircumflexacute,
	KEY_ACIRCUMFLEXGRAVE=		XK_Acircumflexgrave,
	KEY_ACIRCUMFLEXHOOK=		XK_Acircumflexhook,
	KEY_ACIRCUMFLEXTILDE=		XK_Acircumflextilde,
	KEY_ACIRCUMFLEXBELOWDOT=		XK_Acircumflexbelowdot,
	KEY_ABREVEACUTE=		XK_Abreveacute,
	KEY_ABREVEGRAVE=		XK_Abrevegrave,
	KEY_ABREVEHOOK=		XK_Abrevehook,
	KEY_ABREVETILDE=		XK_Abrevetilde,
	KEY_ABREVEBELOWDOT=		XK_Abrevebelowdot,
	KEY_EBELOWDOT=		XK_Ebelowdot,
	KEY_EHOOK=		XK_Ehook,
	KEY_ETILDE=		XK_Etilde,
	KEY_ECIRCUMFLEXACUTE=		XK_Ecircumflexacute,
	KEY_ECIRCUMFLEXGRAVE=		XK_Ecircumflexgrave,
	KEY_ECIRCUMFLEXHOOK=		XK_Ecircumflexhook,
	KEY_ECIRCUMFLEXTILDE=		XK_Ecircumflextilde,
	KEY_ECIRCUMFLEXBELOWDOT=		XK_Ecircumflexbelowdot,
	KEY_IHOOK=		XK_Ihook,
	KEY_IBELOWDOT=		XK_Ibelowdot,
	KEY_OBELOWDOT=		XK_Obelowdot,
	KEY_OHOOK=		XK_Ohook,
	KEY_OCIRCUMFLEXACUTE=		XK_Ocircumflexacute,
	KEY_OCIRCUMFLEXGRAVE=		XK_Ocircumflexgrave,
	KEY_OCIRCUMFLEXHOOK=		XK_Ocircumflexhook,
	KEY_OCIRCUMFLEXTILDE=		XK_Ocircumflextilde,
	KEY_OCIRCUMFLEXBELOWDOT=		XK_Ocircumflexbelowdot,
	KEY_OHORNACUTE=		XK_Ohornacute,
	KEY_OHORNGRAVE=		XK_Ohorngrave,
	KEY_OHORNHOOK=		XK_Ohornhook,
	KEY_OHORNTILDE=		XK_Ohorntilde,
	KEY_OHORNBELOWDOT=		XK_Ohornbelowdot,
	KEY_UBELOWDOT=		XK_Ubelowdot,
	KEY_UHOOK=		XK_Uhook,
	KEY_UHORNACUTE=		XK_Uhornacute,
	KEY_UHORNGRAVE=		XK_Uhorngrave,
	KEY_UHORNHOOK=		XK_Uhornhook,
	KEY_UHORNTILDE=		XK_Uhorntilde,
	KEY_UHORNBELOWDOT=		XK_Uhornbelowdot,
	KEY_YBELOWDOT=		XK_Ybelowdot,
	KEY_YHOOK=		XK_Yhook,
	KEY_YTILDE=		XK_Ytilde,
	KEY_OHORN=		XK_Ohorn,
	KEY_UHORN=		XK_Uhorn,
	#endif
	#ifdef XK_XKB_KEYS
	KEY_ISO_LOCK=		XK_ISO_Lock,
	KEY_ISO_LEVEL2_LATCH=		XK_ISO_Level2_Latch,
	KEY_ISO_LEVEL3_SHIFT=		XK_ISO_Level3_Shift,
	KEY_ISO_LEVEL3_LATCH=		XK_ISO_Level3_Latch,
	KEY_ISO_LEVEL3_LOCK=		XK_ISO_Level3_Lock,
	KEY_ISO_LEVEL5_SHIFT=		XK_ISO_Level5_Shift,
	KEY_ISO_LEVEL5_LATCH=		XK_ISO_Level5_Latch,
	KEY_ISO_LEVEL5_LOCK=		XK_ISO_Level5_Lock,
	KEY_ISO_GROUP_SHIFT=		XK_ISO_Group_Shift,
	KEY_ISO_GROUP_LATCH=		XK_ISO_Group_Latch,
	KEY_ISO_GROUP_LOCK=		XK_ISO_Group_Lock,
	KEY_ISO_NEXT_GROUP=		XK_ISO_Next_Group,
	KEY_ISO_NEXT_GROUP_LOCK=		XK_ISO_Next_Group_Lock,
	KEY_ISO_PREV_GROUP=		XK_ISO_Prev_Group,
	KEY_ISO_PREV_GROUP_LOCK=		XK_ISO_Prev_Group_Lock,
	KEY_ISO_FIRST_GROUP=		XK_ISO_First_Group,
	KEY_ISO_FIRST_GROUP_LOCK=		XK_ISO_First_Group_Lock,
	KEY_ISO_LAST_GROUP=		XK_ISO_Last_Group,
	KEY_ISO_LAST_GROUP_LOCK=		XK_ISO_Last_Group_Lock,
	KEY_ISO_LEFT_TAB=		XK_ISO_Left_Tab,
	KEY_ISO_MOVE_LINE_UP=		XK_ISO_Move_Line_Up,
	KEY_ISO_MOVE_LINE_DOWN=		XK_ISO_Move_Line_Down,
	KEY_ISO_PARTIAL_LINE_UP=		XK_ISO_Partial_Line_Up,
	KEY_ISO_PARTIAL_LINE_DOWN=		XK_ISO_Partial_Line_Down,
	KEY_ISO_PARTIAL_SPACE_LEFT=		XK_ISO_Partial_Space_Left,
	KEY_ISO_PARTIAL_SPACE_RIGHT=		XK_ISO_Partial_Space_Right,
	KEY_ISO_SET_MARGIN_LEFT=		XK_ISO_Set_Margin_Left,
	KEY_ISO_SET_MARGIN_RIGHT=		XK_ISO_Set_Margin_Right,
	KEY_ISO_RELEASE_MARGIN_LEFT=		XK_ISO_Release_Margin_Left,
	KEY_ISO_RELEASE_MARGIN_RIGHT=		XK_ISO_Release_Margin_Right,
	KEY_ISO_RELEASE_BOTH_MARGINS=		XK_ISO_Release_Both_Margins,
	KEY_ISO_FAST_CURSOR_LEFT=		XK_ISO_Fast_Cursor_Left,
	KEY_ISO_FAST_CURSOR_RIGHT=		XK_ISO_Fast_Cursor_Right,
	KEY_ISO_FAST_CURSOR_UP=		XK_ISO_Fast_Cursor_Up,
	KEY_ISO_FAST_CURSOR_DOWN=		XK_ISO_Fast_Cursor_Down,
	KEY_ISO_CONTINUOUS_UNDERLINE=		XK_ISO_Continuous_Underline,
	KEY_ISO_DISCONTINUOUS_UNDERLINE=		XK_ISO_Discontinuous_Underline,
	KEY_ISO_EMPHASIZE=		XK_ISO_Emphasize,
	KEY_ISO_CENTER_OBJECT=		XK_ISO_Center_Object,
	KEY_ISO_ENTER=		XK_ISO_Enter,
	KEY_DEAD_GRAVE=		XK_dead_grave,
	KEY_DEAD_ACUTE=		XK_dead_acute,
	KEY_DEAD_CIRCUMFLEX=		XK_dead_circumflex,
	KEY_DEAD_TILDE=		XK_dead_tilde,
	KEY_DEAD_PERISPOMENI=		XK_dead_perispomeni,
	KEY_DEAD_MACRON=		XK_dead_macron,
	KEY_DEAD_BREVE=		XK_dead_breve,
	KEY_DEAD_ABOVEDOT=		XK_dead_abovedot,
	KEY_DEAD_DIAERESIS=		XK_dead_diaeresis,
	KEY_DEAD_ABOVERING=		XK_dead_abovering,
	KEY_DEAD_DOUBLEACUTE=		XK_dead_doubleacute,
	KEY_DEAD_CARON=		XK_dead_caron,
	KEY_DEAD_CEDILLA=		XK_dead_cedilla,
	KEY_DEAD_OGONEK=		XK_dead_ogonek,
	KEY_DEAD_IOTA=		XK_dead_iota,
	KEY_DEAD_VOICED_SOUND=		XK_dead_voiced_sound,
	KEY_DEAD_SEMIVOICED_SOUND=		XK_dead_semivoiced_sound,
	KEY_DEAD_BELOWDOT=		XK_dead_belowdot,
	KEY_DEAD_HOOK=		XK_dead_hook,
	KEY_DEAD_HORN=		XK_dead_horn,
	KEY_DEAD_STROKE=		XK_dead_stroke,
	KEY_DEAD_ABOVECOMMA=		XK_dead_abovecomma,
	KEY_DEAD_PSILI=		XK_dead_psili,
	KEY_DEAD_ABOVEREVERSEDCOMMA=		XK_dead_abovereversedcomma,
	KEY_DEAD_DASIA=		XK_dead_dasia,
	KEY_DEAD_DOUBLEGRAVE=		XK_dead_doublegrave,
	KEY_DEAD_BELOWRING=		XK_dead_belowring,
	KEY_DEAD_BELOWMACRON=		XK_dead_belowmacron,
	KEY_DEAD_BELOWCIRCUMFLEX=		XK_dead_belowcircumflex,
	KEY_DEAD_BELOWTILDE=		XK_dead_belowtilde,
	KEY_DEAD_BELOWBREVE=		XK_dead_belowbreve,
	KEY_DEAD_BELOWDIAERESIS=		XK_dead_belowdiaeresis,
	KEY_DEAD_INVERTEDBREVE=		XK_dead_invertedbreve,
	KEY_DEAD_BELOWCOMMA=		XK_dead_belowcomma,
	KEY_DEAD_CURRENCY=		XK_dead_currency,
	KEY_DEAD_LOWLINE=		XK_dead_lowline,
	KEY_DEAD_ABOVEVERTICALLINE=		XK_dead_aboveverticalline,
	KEY_DEAD_BELOWVERTICALLINE=		XK_dead_belowverticalline,
	KEY_DEAD_LONGSOLIDUSOVERLAY=		XK_dead_longsolidusoverlay,
	KEY_DEAD_A=		XK_dead_a,
	KEY_DEAD_E=		XK_dead_e,
	KEY_DEAD_I=		XK_dead_i,
	KEY_DEAD_O=		XK_dead_o,
	KEY_DEAD_U=		XK_dead_u,
	KEY_DEAD_SMALL_SCHWA=		XK_dead_small_schwa,
	KEY_DEAD_CAPITAL_SCHWA=		XK_dead_capital_schwa,
	KEY_DEAD_GREEK=		XK_dead_greek,
	KEY_FIRST_VIRTUAL_SCREEN=		XK_First_Virtual_Screen,
	KEY_PREV_VIRTUAL_SCREEN=		XK_Prev_Virtual_Screen,
	KEY_NEXT_VIRTUAL_SCREEN=		XK_Next_Virtual_Screen,
	KEY_LAST_VIRTUAL_SCREEN=		XK_Last_Virtual_Screen,
	KEY_TERMINATE_SERVER=		XK_Terminate_Server,
	KEY_ACCESSX_ENABLE=		XK_AccessX_Enable,
	KEY_ACCESSX_FEEDBACK_ENABLE=		XK_AccessX_Feedback_Enable,
	KEY_REPEATKEYS_ENABLE=		XK_RepeatKeys_Enable,
	KEY_SLOWKEYS_ENABLE=		XK_SlowKeys_Enable,
	KEY_BOUNCEKEYS_ENABLE=		XK_BounceKeys_Enable,
	KEY_STICKYKEYS_ENABLE=		XK_StickyKeys_Enable,
	KEY_MOUSEKEYS_ENABLE=		XK_MouseKeys_Enable,
	KEY_MOUSEKEYS_ACCEL_ENABLE=		XK_MouseKeys_Accel_Enable,
	KEY_OVERLAY1_ENABLE=		XK_Overlay1_Enable,
	KEY_OVERLAY2_ENABLE=		XK_Overlay2_Enable,
	KEY_AUDIBLEBELL_ENABLE=		XK_AudibleBell_Enable,
	KEY_POINTER_LEFT=		XK_Pointer_Left,
	KEY_POINTER_RIGHT=		XK_Pointer_Right,
	KEY_POINTER_UP=		XK_Pointer_Up,
	KEY_POINTER_DOWN=		XK_Pointer_Down,
	KEY_POINTER_UPLEFT=		XK_Pointer_UpLeft,
	KEY_POINTER_UPRIGHT=		XK_Pointer_UpRight,
	KEY_POINTER_DOWNLEFT=		XK_Pointer_DownLeft,
	KEY_POINTER_DOWNRIGHT=		XK_Pointer_DownRight,
	KEY_POINTER_BUTTON_DFLT=		XK_Pointer_Button_Dflt,
	KEY_POINTER_BUTTON1=		XK_Pointer_Button1,
	KEY_POINTER_BUTTON2=		XK_Pointer_Button2,
	KEY_POINTER_BUTTON3=		XK_Pointer_Button3,
	KEY_POINTER_BUTTON4=		XK_Pointer_Button4,
	KEY_POINTER_BUTTON5=		XK_Pointer_Button5,
	KEY_POINTER_DBLCLICK_DFLT=		XK_Pointer_DblClick_Dflt,
	KEY_POINTER_DBLCLICK1=		XK_Pointer_DblClick1,
	KEY_POINTER_DBLCLICK2=		XK_Pointer_DblClick2,
	KEY_POINTER_DBLCLICK3=		XK_Pointer_DblClick3,
	KEY_POINTER_DBLCLICK4=		XK_Pointer_DblClick4,
	KEY_POINTER_DBLCLICK5=		XK_Pointer_DblClick5,
	KEY_POINTER_DRAG_DFLT=		XK_Pointer_Drag_Dflt,
	KEY_POINTER_DRAG1=		XK_Pointer_Drag1,
	KEY_POINTER_DRAG2=		XK_Pointer_Drag2,
	KEY_POINTER_DRAG3=		XK_Pointer_Drag3,
	KEY_POINTER_DRAG4=		XK_Pointer_Drag4,
	KEY_POINTER_DRAG5=		XK_Pointer_Drag5,
	KEY_POINTER_ENABLEKEYS=		XK_Pointer_EnableKeys,
	KEY_POINTER_ACCELERATE=		XK_Pointer_Accelerate,
	KEY_POINTER_DFLTBTNNEXT=		XK_Pointer_DfltBtnNext,
	KEY_POINTER_DFLTBTNPREV=		XK_Pointer_DfltBtnPrev,
	KEY_CH=		XK_ch,
	KEY_C_H=		XK_c_h,
	#endif
	#elif __WXMSW__
	KEY_CANCEL=		VK_CANCEL,
	KEY_BACK=		VK_BACK,
	KEY_TAB=		VK_TAB,
	KEY_CLEAR=		VK_CLEAR,
	KEY_RETURN=		VK_RETURN,
	KEY_SHIFT=		VK_SHIFT,
	KEY_CONTROL=		VK_CONTROL,
	KEY_MENU=		VK_MENU,
	KEY_PAUSE=		VK_PAUSE,
	KEY_CAPITAL=		VK_CAPITAL,
	KEY_KANA=		VK_KANA,
	KEY_HANGEUL=		VK_HANGEUL,
	KEY_HANGUL=		VK_HANGUL,
	KEY_JUNJA=		VK_JUNJA,
	KEY_FINAL=		VK_FINAL,
	KEY_HANJA=		VK_HANJA,
	KEY_KANJI=		VK_KANJI,
	KEY_ESCAPE=		VK_ESCAPE,
	KEY_CONVERT=		VK_CONVERT,
	KEY_NONCONVERT=		VK_NONCONVERT,
	KEY_ACCEPT=		VK_ACCEPT,
	KEY_MODECHANGE=		VK_MODECHANGE,
	KEY_SPACE=		VK_SPACE,
	KEY_PRIOR=		VK_PRIOR,
	KEY_NEXT=		VK_NEXT,
	KEY_END=		VK_END,
	KEY_HOME=		VK_HOME,
	KEY_LEFT=		VK_LEFT,
	KEY_UP=		VK_UP,
	KEY_RIGHT=		VK_RIGHT,
	KEY_DOWN=		VK_DOWN,
	KEY_SELECT=		VK_SELECT,
	KEY_PRINT=		VK_PRINT,
	KEY_EXECUTE=		VK_EXECUTE,
	KEY_SNAPSHOT=		VK_SNAPSHOT,
	KEY_INSERT=		VK_INSERT,
	KEY_DELETE=		VK_DELETE,
	KEY_HELP=		VK_HELP,
	KEY_LWIN=		VK_LWIN,
	KEY_RWIN=		VK_RWIN,
	KEY_APPS=		VK_APPS,
	KEY_SLEEP=		VK_SLEEP,
	KEY_NUMPAD0=		VK_NUMPAD0,
	KEY_NUMPAD1=		VK_NUMPAD1,
	KEY_NUMPAD2=		VK_NUMPAD2,
	KEY_NUMPAD3=		VK_NUMPAD3,
	KEY_NUMPAD4=		VK_NUMPAD4,
	KEY_NUMPAD5=		VK_NUMPAD5,
	KEY_NUMPAD6=		VK_NUMPAD6,
	KEY_NUMPAD7=		VK_NUMPAD7,
	KEY_NUMPAD8=		VK_NUMPAD8,
	KEY_NUMPAD9=		VK_NUMPAD9,
	KEY_MULTIPLY=		VK_MULTIPLY,
	KEY_ADD=		VK_ADD,
	KEY_SEPARATOR=		VK_SEPARATOR,
	KEY_SUBTRACT=		VK_SUBTRACT,
	KEY_DECIMAL=		VK_DECIMAL,
	KEY_DIVIDE=		VK_DIVIDE,
	KEY_F1=		VK_F1,
	KEY_F2=		VK_F2,
	KEY_F3=		VK_F3,
	KEY_F4=		VK_F4,
	KEY_F5=		VK_F5,
	KEY_F6=		VK_F6,
	KEY_F7=		VK_F7,
	KEY_F8=		VK_F8,
	KEY_F9=		VK_F9,
	KEY_F10=		VK_F10,
	KEY_F11=		VK_F11,
	KEY_F12=		VK_F12,
	KEY_F13=		VK_F13,
	KEY_F14=		VK_F14,
	KEY_F15=		VK_F15,
	KEY_F16=		VK_F16,
	KEY_F17=		VK_F17,
	KEY_F18=		VK_F18,
	KEY_F19=		VK_F19,
	KEY_F20=		VK_F20,
	KEY_F21=		VK_F21,
	KEY_F22=		VK_F22,
	KEY_F23=		VK_F23,
	KEY_F24=		VK_F24,
	KEY_NUMLOCK=		VK_NUMLOCK,
	KEY_SCROLL=		VK_SCROLL,
	KEY_OEM_NEC_EQUAL=		VK_OEM_NEC_EQUAL,
	KEY_OEM_FJ_JISHO=		VK_OEM_FJ_JISHO,
	KEY_OEM_FJ_MASSHOU=		VK_OEM_FJ_MASSHOU,
	KEY_OEM_FJ_TOUROKU=		VK_OEM_FJ_TOUROKU,
	KEY_OEM_FJ_LOYA=		VK_OEM_FJ_LOYA,
	KEY_OEM_FJ_ROYA=		VK_OEM_FJ_ROYA,
	KEY_LSHIFT=		VK_LSHIFT,
	KEY_RSHIFT=		VK_RSHIFT,
	KEY_LCONTROL=		VK_LCONTROL,
	KEY_RCONTROL=		VK_RCONTROL,
	KEY_LMENU=		VK_LMENU,
	KEY_RMENU=		VK_RMENU,
	KEY_BROWSER_BACK=		VK_BROWSER_BACK,
	KEY_BROWSER_FORWARD=		VK_BROWSER_FORWARD,
	KEY_BROWSER_REFRESH=		VK_BROWSER_REFRESH,
	KEY_BROWSER_STOP=		VK_BROWSER_STOP,
	KEY_BROWSER_SEARCH=		VK_BROWSER_SEARCH,
	KEY_BROWSER_FAVORITES=		VK_BROWSER_FAVORITES,
	KEY_BROWSER_HOME=		VK_BROWSER_HOME,
	KEY_VOLUME_MUTE=		VK_VOLUME_MUTE,
	KEY_VOLUME_DOWN=		VK_VOLUME_DOWN,
	KEY_VOLUME_UP=		VK_VOLUME_UP,
	KEY_MEDIA_NEXT_TRACK=		VK_MEDIA_NEXT_TRACK,
	KEY_MEDIA_PREV_TRACK=		VK_MEDIA_PREV_TRACK,
	KEY_MEDIA_STOP=		VK_MEDIA_STOP,
	KEY_MEDIA_PLAY_PAUSE=		VK_MEDIA_PLAY_PAUSE,
	KEY_LAUNCH_MAIL=		VK_LAUNCH_MAIL,
	KEY_LAUNCH_MEDIA_SELECT=		VK_LAUNCH_MEDIA_SELECT,
	KEY_LAUNCH_APP1=		VK_LAUNCH_APP1,
	KEY_LAUNCH_APP2=		VK_LAUNCH_APP2,
	KEY_OEM_1=		VK_OEM_1,
	KEY_OEM_PLUS=		VK_OEM_PLUS,
	KEY_OEM_COMMA=		VK_OEM_COMMA,
	KEY_OEM_MINUS=		VK_OEM_MINUS,
	KEY_OEM_PERIOD=		VK_OEM_PERIOD,
	KEY_OEM_2=		VK_OEM_2,
	KEY_OEM_3=		VK_OEM_3,
	KEY_OEM_4=		VK_OEM_4,
	KEY_OEM_5=		VK_OEM_5,
	KEY_OEM_6=		VK_OEM_6,
	KEY_OEM_7=		VK_OEM_7,
	KEY_OEM_8=		VK_OEM_8,
	KEY_OEM_AX=		VK_OEM_AX,
	KEY_OEM_102=		VK_OEM_102,
	KEY_ICO_HELP=		VK_ICO_HELP,
	KEY_ICO_00=		VK_ICO_00,
	KEY_PROCESSKEY=		VK_PROCESSKEY,
	KEY_ICO_CLEAR=		VK_ICO_CLEAR,
	KEY_PACKET=		VK_PACKET,
	KEY_OEM_RESET=		VK_OEM_RESET,
	KEY_OEM_JUMP=		VK_OEM_JUMP,
	KEY_OEM_PA1=		VK_OEM_PA1,
	KEY_OEM_PA2=		VK_OEM_PA2,
	KEY_OEM_PA3=		VK_OEM_PA3,
	KEY_OEM_WSCTRL=		VK_OEM_WSCTRL,
	KEY_OEM_CUSEL=		VK_OEM_CUSEL,
	KEY_OEM_ATTN=		VK_OEM_ATTN,
	KEY_OEM_FINISH=		VK_OEM_FINISH,
	KEY_OEM_COPY=		VK_OEM_COPY,
	KEY_OEM_AUTO=		VK_OEM_AUTO,
	KEY_OEM_ENLW=		VK_OEM_ENLW,
	KEY_OEM_BACKTAB=		VK_OEM_BACKTAB,
	KEY_ATTN=		VK_ATTN,
	KEY_CRSEL=		VK_CRSEL,
	KEY_EXSEL=		VK_EXSEL,
	KEY_EREOF=		VK_EREOF,
	KEY_PLAY=		VK_PLAY,
	KEY_ZOOM=		VK_ZOOM,
	KEY_NONAME=		VK_NONAME,
	KEY_PA1=		VK_PA1,
	KEY_OEM_CLEAR=		VK_OEM_CLEAR,
	#endif
	KEY_A=		'A',
	KEY_B=		'B',
	KEY_C=		'C',
	KEY_D=		'D',
	KEY_E=		'E',
	KEY_F=		'F',
	KEY_G=		'G',
	KEY_H=		'H',
	KEY_I=		'I',
	KEY_J=		'J',
	KEY_K=		'K',
	KEY_L=		'L',
	KEY_M=		'M',
	KEY_N=		'N',
	KEY_O=		'O',
	KEY_P=		'P',
	KEY_Q=		'Q',
	KEY_R=		'R',
	KEY_S=		'S',
	KEY_T=		'T',
	KEY_U=		'U',
	KEY_V=		'V',
	KEY_W=		'W',
	KEY_X=		'X',
	KEY_Y=		'Y',
	KEY_Z=		'Z',
	KEY_NONE=		-1
};
                             
inline Modifier_e operator|(Modifier_e val1, Modifier_e val2)
{
	unsigned int val = (unsigned int)val1|(unsigned int)val2;
	return static_cast<Modifier_e>(val);
}

// *****************************************************************************
// Class ShortcutKey
// *****************************************************************************

//! \brief Représente un raccourci clavier constituer d'un modificateur et d'une touche.
class ShortcutKey
{
	public:
		//! \brief Constructeur.
		//! Ce Constructeur ne construis pas un raccourcis valide. \ref isOk() renverra false.
		ShortcutKey();
		
		//! \brief Constructeur.
		//! \param modifiers peut être combiner avec tout les valeurs de \ref Modifier_e ex:KEY_MODIFIER_SUPER|KEY_MODIFIER_CONTROL)
		//! \param key c'est la touche du raccourci.
		ShortcutKey(Modifier_e modifiers, Key_e key);
		
		bool operator<(ShortcutKey const& ins)const;
		bool operator==(ShortcutKey const& ins)const;
		bool operator!=(ShortcutKey const& ins)const;
		
		//! \brief Obtenir la touche.
		Key_e getKey()const;
		
		//! \brief Obtenir le modificateur.
		//! \return C'est une valeur combiner de \ref Modifier_e.
		Modifier_e getModifiers()const;
		
		//! \brief Vérifie la validité du raccourcie.
		bool isOk()const;
		
		//! \brief Converti un \ref ShortcutKey en string.
		//! \param shortcut le raccourci en version \ref ShortcutKey.
		//! \return Le raccourci en version string.
		static wxString shortcutKeyToString(ShortcutKey const& shortcut);
		
		//! \brief Converti un raccourci, de sa version string en \ref ShortcutKey.
		//!
		//! Le raccourci doit être de la forme modificateur+caractère (ex:"alt+shift+f").
		//! \param shortcut le raccourci en version string.
		//! \return Le raccourci en version \ref ShortcutKey. Vous pouver verifier la validiter du racoursen
		//! en appeler \ref getCharKey() et \ref getModifiers(). Si  getCharKey() retourne '\n' ou/et si \ref getModifiers() retourne \b KEY_MODIFIER_NONE
		//! votre raccourcis n'est pas valide. Sinon vous pouver appeler \ref isOk() qui fais sa pour vous.
		//! \see Modifier_e
		static ShortcutKey stringToShortcutKey(wxString const& shortcut);
		
		static wxString modifierToString(Modifier_e modifier);
		static Modifier_e stringToModifier(wxString modifier);
		static wxArrayString getModifiersStrings();
		
		static wxString keyToString(Key_e key);
		static Key_e stringToKey(wxString key);
		static wxArrayString getKeysStrings();
		
	private:
		//! \brief Le modificateur.
		Modifier_e _modifiers;
		//! \brief La touche.
		Key_e _key;
};

// *****************************************************************************
// Class ShortcutEvent
// *****************************************************************************

//! \brief Événement lier au raccourci clavier.
//! \see Shortcut
class ShortcutEvent: public wxEvent
{
	public:
		//! \brief Constructeur.
		//! \param eventType le type de l'événement. Si vous en crée pas de nouveau, \a EVT_SHORTCUT devait être passer.
		//! \param modifiers peut être combiner avec tout les valeurs de \ref Modifier_e ex:KEY_MODIFIER_UPER|KEY_MODIFIER_CONTROL)
		//! \param key c'est la touche du raccourci.
		ShortcutEvent(wxEventType eventType, Modifier_e modifiers, Key_e key);
		
		//! \brief Constructeur.
		//! \param eventType le type de l'événement. Si vous en crée pas de nouveau, \a EVT_SHORTCUT devait être passer.
		//! \param shortcutKey le raccourci.
		ShortcutEvent(wxEventType eventType, ShortcutKey const& shortcutKey);
		
		//! \brief Clone.
		//! \return une nouvelle instance.
		virtual wxEvent* Clone()const;
		
		//! \brief Obtenir la touche.
		Key_e getKey()const;
		
		//! \brief Obtenir le modificateur.
		//! \return C'est une valeur combiner de \ref Modifier_e.
		Modifier_e getModifiers()const;
		
		//! \brief Obtenir le raccourci.
		//! \return Le raccourci.
		ShortcutKey const& getShortcutKey()const;
		
	private:
		//! \brief Le raccourci.
		ShortcutKey _shortcutKey;
};

//! \brief Déclaration de l'événement EVT_SHORTCUT.
wxDECLARE_EVENT(EVT_SHORTCUT, ShortcutEvent);

// *****************************************************************************
// Class ShortcutThread
// *****************************************************************************

//! \brief C'est le thread qui installe/désinstalle les raccourcis au-prés
//! de l'os et qui lève un événement de type \ref ShortcutEvent lorsque
//! qu'un raccourci est détecter presser sur le clavier.
//!
//! \note Avant de supprimer une instances de cette classe assurez vous de bien
//! avoir unregister touts les raccourcis avec \ref unregisterShortcut().
class ShortcutThread : protected wxThread
{
	public:
		#ifdef __WXMSW__
		ShortcutThread(wxEvtHandler *owner, std::vector<ShortcutKey>const& shortcutKeys);
		#else
		//! \brief Constructeur.
		//! \param owner est un wxEvtHandler qui est utiliser pour générer les événements.
		ShortcutThread(wxEvtHandler *owner);
		#endif
		
		//! \brief Destructeur.
		~ShortcutThread();
		
		//! \brief Active un raccourci.
		//! \param shortcutKey est le raccourci à activer.
		void registerShortcut(ShortcutKey const& shortcutKey);
		
		//! \brief Désactive un raccourci.
		//! \param shortcutKey est le raccourci à Désactive.
		void unregisterShortcut(ShortcutKey const& shortcutKey);
		
	protected:
		wxThread::ExitCode Entry();
		void halt();
    
	private:
		//! \brief Utiliser pour générer les événements.
		wxEvtHandler *_owner; 
		
		//! \brief Mutex pour protéger les variable de communication avec le thread.
		volatile bool _mutexCommunicationThread;
		
		//! \brief Comunique le ShortcutKey au thread.
		ShortcutKey const* _shortcutKeyCommunicationThread;
		enum CommunicationThread
		{
			CUMMUNICATION_THREAD_REGISTER,
			CUMMUNICATION_THREAD_UNREGISTER,
			CUMMUNICATION_THREAD_QUIT,
			CUMMUNICATION_THREAD_NONE
		};
		//! \brief Action à communiquer au thread.
		volatile CommunicationThread _communicationThread;
		
		
		#if defined(__UNIX__)
		Display *_display;
		Window _root;
		Window _interCommunication;
		XEvent _event;
		#elif defined(__WXMSW__)
		MSG _msgEvent;
		std::vector<ShortcutKey>const& _shortcutKeys;
		#endif
};

// *****************************************************************************
// Class Shortcut
// *****************************************************************************

//! \brief Interface utilisateur pour les gestions des raccourci clavier globaux.
//!
//! Voici un exemple d'utilisation. Dans cette exemple la classe App hérite de
//! la class wxApp.
//! \code
//! bool App::OnInit()
//! {
//! 	//Création d'un objet Shortcut.
//! 	_shortcut = new Shortcut(this);	
//! 	
//! 	//Création d'un raccourci, touche super+a 
//! 	_shortcut->creat(KEY_MODIFIER_SUPER, 'a');
//! 	
//! 	//Création d'un raccourci, touche super+b
//! 	_shortcut->creat(KEY_MODIFIER_SUPER, 'b');
//!
//! 	//Création d'un raccourci, touche shift+super+a
//! 	ShortcutKey shortcutKey(ShortcutKey::stringToShortcutKey("shift+super+a"));
//! 	_shortcut->creat(shortcutKey);
//! 	
//! 	//Création d'un raccourci, touche super+ctrl+a 
//! 	_shortcut->creat(KEY_MODIFIER_SUPER|KEY_MODIFIER_CONTROL, 'a');
//! 
//! 	return true;
//! }
//! 
//! void App::OnShortcut(ShortcutEvent& event)
//! {
//! 	std::cout << "OnShortcut -> " << event.getCharKey() << " : ";
//! 						std::cout << event.getModifiers() << std::endl;		
//! }
//! \endcode
class Shortcut
{
	public:
		//! \brief Constructeur.
		//! \param owner est un wxEvtHandler qui est utiliser pour générer les événements.
		//! \note Par défaut les raccourcis sont activés. Il n'est donc pas nécessaire d'appeler la méthode \ref enable().
		Shortcut(wxEvtHandler* owner);
		
		//! \brief Destructeur.
		~Shortcut();
		
		//! \brief Créé un nouveau raccourci.
		//! \code
		//! //Création d'un raccourci, touche "super+ctrl+a" 
		//! 	id = _shortcut->creat(KEY_MODIFIER_SUPER|KEY_MODIFIER_CONTROL), 'a');
		//! \endcode
		//! \param modifiers Le modificateur lier au raccourci, peut être une combinaison de \ref Modifier_e.
		//! \param key la touche du racourci.
		//! \return un nouveau id lier au raccourci. L'id est générer avec wxNewId().
		void creat(Modifier_e modifiers, Key_e key);
		
		//! \brief Créé un nouveau raccourci.
		//! \param shortcutKey Le raccourci.
		//! \return un nouveau id lier au raccourci. L'id est générer avec wxNewId().
		void creat(ShortcutKey const& shortcutKey);
		
		//! \brief Supprimer un raccourci.
		//! \param modifiers Le modificateur lier au raccourci, peut être une combinaison de \ref Modifier_e.
		//! \param key la touche du raccourci.
		void remove(Modifier_e modifiers, Key_e key);
		
		//! \brief Supprimer un raccourci.
		//! \param shortcutKey Le raccourci à supprimer.
		void remove(ShortcutKey const& shortcutKey);
		
		//! \brief Supprimer touts les raccourcis.
		void removeAll();
		
		//! \brief Active ou désactive les raccourcis.
		//! Par défaut les raccourcis sont activés.
		//! \param val true pour activer et false pour désactiver.
		void enable(bool val = true);
		
		//! \brief Pour savoir si les raccourcis son activer ou pas.
		bool isEnable();
		
	private:
		//! \brief Les raccourcis qui on été crée.
		//! \see creat()
		std::vector<ShortcutKey> _shortcutKeys;
		
		ShortcutThread* _thread;
		
		//! \brief utiliser pour générer les événements.
		wxEvtHandler *_owner;
		
		//! \brief Raccourci activer ou pas.
		//! \see enable()
		bool _enable;
};

#endif //SHORTCUT_H
